// Copyright 2025 Lukas Schmidt
// SPDX-License-Identifier: MIT

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.5
// source: zhiplugin/v1/store.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StoreService_Capabilities_FullMethodName       = "/zhiplugin.v1.StoreService/Capabilities"
	StoreService_AuthMethods_FullMethodName        = "/zhiplugin.v1.StoreService/AuthMethods"
	StoreService_Login_FullMethodName              = "/zhiplugin.v1.StoreService/Login"
	StoreService_ListTrees_FullMethodName          = "/zhiplugin.v1.StoreService/ListTrees"
	StoreService_DeleteTree_FullMethodName         = "/zhiplugin.v1.StoreService/DeleteTree"
	StoreService_GetValues_FullMethodName          = "/zhiplugin.v1.StoreService/GetValues"
	StoreService_PutValues_FullMethodName          = "/zhiplugin.v1.StoreService/PutValues"
	StoreService_DeleteValues_FullMethodName       = "/zhiplugin.v1.StoreService/DeleteValues"
	StoreService_ListTreeVersions_FullMethodName   = "/zhiplugin.v1.StoreService/ListTreeVersions"
	StoreService_GetTreeVersion_FullMethodName     = "/zhiplugin.v1.StoreService/GetTreeVersion"
	StoreService_RollbackTree_FullMethodName       = "/zhiplugin.v1.StoreService/RollbackTree"
	StoreService_DeleteTreeVersion_FullMethodName  = "/zhiplugin.v1.StoreService/DeleteTreeVersion"
	StoreService_ListValueVersions_FullMethodName  = "/zhiplugin.v1.StoreService/ListValueVersions"
	StoreService_GetValueVersion_FullMethodName    = "/zhiplugin.v1.StoreService/GetValueVersion"
	StoreService_RollbackValue_FullMethodName      = "/zhiplugin.v1.StoreService/RollbackValue"
	StoreService_DeleteValueVersion_FullMethodName = "/zhiplugin.v1.StoreService/DeleteValueVersion"
	StoreService_InitEncryption_FullMethodName     = "/zhiplugin.v1.StoreService/InitEncryption"
	StoreService_RotateEncryption_FullMethodName   = "/zhiplugin.v1.StoreService/RotateEncryption"
	StoreService_GrantAccess_FullMethodName        = "/zhiplugin.v1.StoreService/GrantAccess"
	StoreService_RevokeAccess_FullMethodName       = "/zhiplugin.v1.StoreService/RevokeAccess"
	StoreService_ListAccess_FullMethodName         = "/zhiplugin.v1.StoreService/ListAccess"
)

// StoreServiceClient is the client API for StoreService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// StoreService is the gRPC interface every zhi store plugin must implement.
// Store plugins persist, retrieve, and delete configuration values within
// named trees with granular, value-level operations.
type StoreServiceClient interface {
	// Capabilities reports the store's supported features.
	Capabilities(ctx context.Context, in *StoreCapabilitiesRequest, opts ...grpc.CallOption) (*StoreCapabilitiesResponse, error)
	// AuthMethods returns the authentication methods supported by this store.
	AuthMethods(ctx context.Context, in *AuthMethodsRequest, opts ...grpc.CallOption) (*AuthMethodsResponse, error)
	// Login authenticates with the store using the given method and credentials.
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	// ListTrees returns all tree IDs the current identity has access to.
	ListTrees(ctx context.Context, in *ListTreesRequest, opts ...grpc.CallOption) (*ListTreesResponse, error)
	// DeleteTree removes an entire tree and all its versions/values.
	DeleteTree(ctx context.Context, in *DeleteTreeRequest, opts ...grpc.CallOption) (*DeleteTreeResponse, error)
	// GetValues retrieves specific values from a tree by their paths.
	GetValues(ctx context.Context, in *GetValuesRequest, opts ...grpc.CallOption) (*GetValuesResponse, error)
	// PutValues writes specific values to a tree.
	PutValues(ctx context.Context, in *PutValuesRequest, opts ...grpc.CallOption) (*PutValuesResponse, error)
	// DeleteValues removes specific values from a tree.
	DeleteValues(ctx context.Context, in *DeleteValuesRequest, opts ...grpc.CallOption) (*DeleteValuesResponse, error)
	// ListTreeVersions returns version identifiers for a tree (VersioningTree).
	ListTreeVersions(ctx context.Context, in *ListTreeVersionsRequest, opts ...grpc.CallOption) (*ListTreeVersionsResponse, error)
	// GetTreeVersion retrieves specific values from a specific tree version.
	GetTreeVersion(ctx context.Context, in *GetTreeVersionRequest, opts ...grpc.CallOption) (*GetTreeVersionResponse, error)
	// RollbackTree restores a tree to a previous version.
	RollbackTree(ctx context.Context, in *RollbackTreeRequest, opts ...grpc.CallOption) (*RollbackTreeResponse, error)
	// DeleteTreeVersion permanently removes a single tree version.
	DeleteTreeVersion(ctx context.Context, in *DeleteTreeVersionRequest, opts ...grpc.CallOption) (*DeleteTreeVersionResponse, error)
	// ListValueVersions returns version identifiers for a specific value (VersioningValue).
	ListValueVersions(ctx context.Context, in *ListValueVersionsRequest, opts ...grpc.CallOption) (*ListValueVersionsResponse, error)
	// GetValueVersion retrieves a specific version of a single value.
	GetValueVersion(ctx context.Context, in *GetValueVersionRequest, opts ...grpc.CallOption) (*GetValueVersionResponse, error)
	// RollbackValue restores a value to a previous version.
	RollbackValue(ctx context.Context, in *RollbackValueRequest, opts ...grpc.CallOption) (*RollbackValueResponse, error)
	// DeleteValueVersion permanently removes a single value version.
	DeleteValueVersion(ctx context.Context, in *DeleteValueVersionRequest, opts ...grpc.CallOption) (*DeleteValueVersionResponse, error)
	// InitEncryption initializes encryption for the store.
	InitEncryption(ctx context.Context, in *InitEncryptionRequest, opts ...grpc.CallOption) (*InitEncryptionResponse, error)
	// RotateEncryption re-encrypts stored data with a new passphrase.
	RotateEncryption(ctx context.Context, in *RotateEncryptionRequest, opts ...grpc.CallOption) (*RotateEncryptionResponse, error)
	// GrantAccess grants a user access to specific paths within a tree.
	GrantAccess(ctx context.Context, in *GrantAccessRequest, opts ...grpc.CallOption) (*GrantAccessResponse, error)
	// RevokeAccess removes a user's access to specific paths within a tree.
	RevokeAccess(ctx context.Context, in *RevokeAccessRequest, opts ...grpc.CallOption) (*RevokeAccessResponse, error)
	// ListAccess returns the current access permissions for a tree.
	ListAccess(ctx context.Context, in *ListAccessRequest, opts ...grpc.CallOption) (*ListAccessResponse, error)
}

type storeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStoreServiceClient(cc grpc.ClientConnInterface) StoreServiceClient {
	return &storeServiceClient{cc}
}

func (c *storeServiceClient) Capabilities(ctx context.Context, in *StoreCapabilitiesRequest, opts ...grpc.CallOption) (*StoreCapabilitiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StoreCapabilitiesResponse)
	err := c.cc.Invoke(ctx, StoreService_Capabilities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) AuthMethods(ctx context.Context, in *AuthMethodsRequest, opts ...grpc.CallOption) (*AuthMethodsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthMethodsResponse)
	err := c.cc.Invoke(ctx, StoreService_AuthMethods_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, StoreService_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) ListTrees(ctx context.Context, in *ListTreesRequest, opts ...grpc.CallOption) (*ListTreesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTreesResponse)
	err := c.cc.Invoke(ctx, StoreService_ListTrees_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) DeleteTree(ctx context.Context, in *DeleteTreeRequest, opts ...grpc.CallOption) (*DeleteTreeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteTreeResponse)
	err := c.cc.Invoke(ctx, StoreService_DeleteTree_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) GetValues(ctx context.Context, in *GetValuesRequest, opts ...grpc.CallOption) (*GetValuesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetValuesResponse)
	err := c.cc.Invoke(ctx, StoreService_GetValues_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) PutValues(ctx context.Context, in *PutValuesRequest, opts ...grpc.CallOption) (*PutValuesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PutValuesResponse)
	err := c.cc.Invoke(ctx, StoreService_PutValues_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) DeleteValues(ctx context.Context, in *DeleteValuesRequest, opts ...grpc.CallOption) (*DeleteValuesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteValuesResponse)
	err := c.cc.Invoke(ctx, StoreService_DeleteValues_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) ListTreeVersions(ctx context.Context, in *ListTreeVersionsRequest, opts ...grpc.CallOption) (*ListTreeVersionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTreeVersionsResponse)
	err := c.cc.Invoke(ctx, StoreService_ListTreeVersions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) GetTreeVersion(ctx context.Context, in *GetTreeVersionRequest, opts ...grpc.CallOption) (*GetTreeVersionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTreeVersionResponse)
	err := c.cc.Invoke(ctx, StoreService_GetTreeVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) RollbackTree(ctx context.Context, in *RollbackTreeRequest, opts ...grpc.CallOption) (*RollbackTreeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RollbackTreeResponse)
	err := c.cc.Invoke(ctx, StoreService_RollbackTree_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) DeleteTreeVersion(ctx context.Context, in *DeleteTreeVersionRequest, opts ...grpc.CallOption) (*DeleteTreeVersionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteTreeVersionResponse)
	err := c.cc.Invoke(ctx, StoreService_DeleteTreeVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) ListValueVersions(ctx context.Context, in *ListValueVersionsRequest, opts ...grpc.CallOption) (*ListValueVersionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListValueVersionsResponse)
	err := c.cc.Invoke(ctx, StoreService_ListValueVersions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) GetValueVersion(ctx context.Context, in *GetValueVersionRequest, opts ...grpc.CallOption) (*GetValueVersionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetValueVersionResponse)
	err := c.cc.Invoke(ctx, StoreService_GetValueVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) RollbackValue(ctx context.Context, in *RollbackValueRequest, opts ...grpc.CallOption) (*RollbackValueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RollbackValueResponse)
	err := c.cc.Invoke(ctx, StoreService_RollbackValue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) DeleteValueVersion(ctx context.Context, in *DeleteValueVersionRequest, opts ...grpc.CallOption) (*DeleteValueVersionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteValueVersionResponse)
	err := c.cc.Invoke(ctx, StoreService_DeleteValueVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) InitEncryption(ctx context.Context, in *InitEncryptionRequest, opts ...grpc.CallOption) (*InitEncryptionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitEncryptionResponse)
	err := c.cc.Invoke(ctx, StoreService_InitEncryption_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) RotateEncryption(ctx context.Context, in *RotateEncryptionRequest, opts ...grpc.CallOption) (*RotateEncryptionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RotateEncryptionResponse)
	err := c.cc.Invoke(ctx, StoreService_RotateEncryption_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) GrantAccess(ctx context.Context, in *GrantAccessRequest, opts ...grpc.CallOption) (*GrantAccessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GrantAccessResponse)
	err := c.cc.Invoke(ctx, StoreService_GrantAccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) RevokeAccess(ctx context.Context, in *RevokeAccessRequest, opts ...grpc.CallOption) (*RevokeAccessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeAccessResponse)
	err := c.cc.Invoke(ctx, StoreService_RevokeAccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) ListAccess(ctx context.Context, in *ListAccessRequest, opts ...grpc.CallOption) (*ListAccessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAccessResponse)
	err := c.cc.Invoke(ctx, StoreService_ListAccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StoreServiceServer is the server API for StoreService service.
// All implementations must embed UnimplementedStoreServiceServer
// for forward compatibility.
//
// StoreService is the gRPC interface every zhi store plugin must implement.
// Store plugins persist, retrieve, and delete configuration values within
// named trees with granular, value-level operations.
type StoreServiceServer interface {
	// Capabilities reports the store's supported features.
	Capabilities(context.Context, *StoreCapabilitiesRequest) (*StoreCapabilitiesResponse, error)
	// AuthMethods returns the authentication methods supported by this store.
	AuthMethods(context.Context, *AuthMethodsRequest) (*AuthMethodsResponse, error)
	// Login authenticates with the store using the given method and credentials.
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	// ListTrees returns all tree IDs the current identity has access to.
	ListTrees(context.Context, *ListTreesRequest) (*ListTreesResponse, error)
	// DeleteTree removes an entire tree and all its versions/values.
	DeleteTree(context.Context, *DeleteTreeRequest) (*DeleteTreeResponse, error)
	// GetValues retrieves specific values from a tree by their paths.
	GetValues(context.Context, *GetValuesRequest) (*GetValuesResponse, error)
	// PutValues writes specific values to a tree.
	PutValues(context.Context, *PutValuesRequest) (*PutValuesResponse, error)
	// DeleteValues removes specific values from a tree.
	DeleteValues(context.Context, *DeleteValuesRequest) (*DeleteValuesResponse, error)
	// ListTreeVersions returns version identifiers for a tree (VersioningTree).
	ListTreeVersions(context.Context, *ListTreeVersionsRequest) (*ListTreeVersionsResponse, error)
	// GetTreeVersion retrieves specific values from a specific tree version.
	GetTreeVersion(context.Context, *GetTreeVersionRequest) (*GetTreeVersionResponse, error)
	// RollbackTree restores a tree to a previous version.
	RollbackTree(context.Context, *RollbackTreeRequest) (*RollbackTreeResponse, error)
	// DeleteTreeVersion permanently removes a single tree version.
	DeleteTreeVersion(context.Context, *DeleteTreeVersionRequest) (*DeleteTreeVersionResponse, error)
	// ListValueVersions returns version identifiers for a specific value (VersioningValue).
	ListValueVersions(context.Context, *ListValueVersionsRequest) (*ListValueVersionsResponse, error)
	// GetValueVersion retrieves a specific version of a single value.
	GetValueVersion(context.Context, *GetValueVersionRequest) (*GetValueVersionResponse, error)
	// RollbackValue restores a value to a previous version.
	RollbackValue(context.Context, *RollbackValueRequest) (*RollbackValueResponse, error)
	// DeleteValueVersion permanently removes a single value version.
	DeleteValueVersion(context.Context, *DeleteValueVersionRequest) (*DeleteValueVersionResponse, error)
	// InitEncryption initializes encryption for the store.
	InitEncryption(context.Context, *InitEncryptionRequest) (*InitEncryptionResponse, error)
	// RotateEncryption re-encrypts stored data with a new passphrase.
	RotateEncryption(context.Context, *RotateEncryptionRequest) (*RotateEncryptionResponse, error)
	// GrantAccess grants a user access to specific paths within a tree.
	GrantAccess(context.Context, *GrantAccessRequest) (*GrantAccessResponse, error)
	// RevokeAccess removes a user's access to specific paths within a tree.
	RevokeAccess(context.Context, *RevokeAccessRequest) (*RevokeAccessResponse, error)
	// ListAccess returns the current access permissions for a tree.
	ListAccess(context.Context, *ListAccessRequest) (*ListAccessResponse, error)
	mustEmbedUnimplementedStoreServiceServer()
}

// UnimplementedStoreServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStoreServiceServer struct{}

func (UnimplementedStoreServiceServer) Capabilities(context.Context, *StoreCapabilitiesRequest) (*StoreCapabilitiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Capabilities not implemented")
}
func (UnimplementedStoreServiceServer) AuthMethods(context.Context, *AuthMethodsRequest) (*AuthMethodsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AuthMethods not implemented")
}
func (UnimplementedStoreServiceServer) Login(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedStoreServiceServer) ListTrees(context.Context, *ListTreesRequest) (*ListTreesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTrees not implemented")
}
func (UnimplementedStoreServiceServer) DeleteTree(context.Context, *DeleteTreeRequest) (*DeleteTreeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteTree not implemented")
}
func (UnimplementedStoreServiceServer) GetValues(context.Context, *GetValuesRequest) (*GetValuesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetValues not implemented")
}
func (UnimplementedStoreServiceServer) PutValues(context.Context, *PutValuesRequest) (*PutValuesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PutValues not implemented")
}
func (UnimplementedStoreServiceServer) DeleteValues(context.Context, *DeleteValuesRequest) (*DeleteValuesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteValues not implemented")
}
func (UnimplementedStoreServiceServer) ListTreeVersions(context.Context, *ListTreeVersionsRequest) (*ListTreeVersionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTreeVersions not implemented")
}
func (UnimplementedStoreServiceServer) GetTreeVersion(context.Context, *GetTreeVersionRequest) (*GetTreeVersionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTreeVersion not implemented")
}
func (UnimplementedStoreServiceServer) RollbackTree(context.Context, *RollbackTreeRequest) (*RollbackTreeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RollbackTree not implemented")
}
func (UnimplementedStoreServiceServer) DeleteTreeVersion(context.Context, *DeleteTreeVersionRequest) (*DeleteTreeVersionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteTreeVersion not implemented")
}
func (UnimplementedStoreServiceServer) ListValueVersions(context.Context, *ListValueVersionsRequest) (*ListValueVersionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListValueVersions not implemented")
}
func (UnimplementedStoreServiceServer) GetValueVersion(context.Context, *GetValueVersionRequest) (*GetValueVersionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetValueVersion not implemented")
}
func (UnimplementedStoreServiceServer) RollbackValue(context.Context, *RollbackValueRequest) (*RollbackValueResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RollbackValue not implemented")
}
func (UnimplementedStoreServiceServer) DeleteValueVersion(context.Context, *DeleteValueVersionRequest) (*DeleteValueVersionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteValueVersion not implemented")
}
func (UnimplementedStoreServiceServer) InitEncryption(context.Context, *InitEncryptionRequest) (*InitEncryptionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InitEncryption not implemented")
}
func (UnimplementedStoreServiceServer) RotateEncryption(context.Context, *RotateEncryptionRequest) (*RotateEncryptionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RotateEncryption not implemented")
}
func (UnimplementedStoreServiceServer) GrantAccess(context.Context, *GrantAccessRequest) (*GrantAccessResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GrantAccess not implemented")
}
func (UnimplementedStoreServiceServer) RevokeAccess(context.Context, *RevokeAccessRequest) (*RevokeAccessResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RevokeAccess not implemented")
}
func (UnimplementedStoreServiceServer) ListAccess(context.Context, *ListAccessRequest) (*ListAccessResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAccess not implemented")
}
func (UnimplementedStoreServiceServer) mustEmbedUnimplementedStoreServiceServer() {}
func (UnimplementedStoreServiceServer) testEmbeddedByValue()                      {}

// UnsafeStoreServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StoreServiceServer will
// result in compilation errors.
type UnsafeStoreServiceServer interface {
	mustEmbedUnimplementedStoreServiceServer()
}

func RegisterStoreServiceServer(s grpc.ServiceRegistrar, srv StoreServiceServer) {
	// If the following call panics, it indicates UnimplementedStoreServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StoreService_ServiceDesc, srv)
}

func _StoreService_Capabilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreCapabilitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).Capabilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreService_Capabilities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).Capabilities(ctx, req.(*StoreCapabilitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_AuthMethods_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthMethodsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).AuthMethods(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreService_AuthMethods_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).AuthMethods(ctx, req.(*AuthMethodsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreService_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_ListTrees_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTreesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).ListTrees(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreService_ListTrees_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).ListTrees(ctx, req.(*ListTreesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_DeleteTree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTreeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).DeleteTree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreService_DeleteTree_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).DeleteTree(ctx, req.(*DeleteTreeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_GetValues_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetValuesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).GetValues(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreService_GetValues_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).GetValues(ctx, req.(*GetValuesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_PutValues_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutValuesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).PutValues(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreService_PutValues_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).PutValues(ctx, req.(*PutValuesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_DeleteValues_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteValuesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).DeleteValues(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreService_DeleteValues_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).DeleteValues(ctx, req.(*DeleteValuesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_ListTreeVersions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTreeVersionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).ListTreeVersions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreService_ListTreeVersions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).ListTreeVersions(ctx, req.(*ListTreeVersionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_GetTreeVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTreeVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).GetTreeVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreService_GetTreeVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).GetTreeVersion(ctx, req.(*GetTreeVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_RollbackTree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RollbackTreeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).RollbackTree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreService_RollbackTree_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).RollbackTree(ctx, req.(*RollbackTreeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_DeleteTreeVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTreeVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).DeleteTreeVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreService_DeleteTreeVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).DeleteTreeVersion(ctx, req.(*DeleteTreeVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_ListValueVersions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListValueVersionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).ListValueVersions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreService_ListValueVersions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).ListValueVersions(ctx, req.(*ListValueVersionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_GetValueVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetValueVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).GetValueVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreService_GetValueVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).GetValueVersion(ctx, req.(*GetValueVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_RollbackValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RollbackValueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).RollbackValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreService_RollbackValue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).RollbackValue(ctx, req.(*RollbackValueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_DeleteValueVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteValueVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).DeleteValueVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreService_DeleteValueVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).DeleteValueVersion(ctx, req.(*DeleteValueVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_InitEncryption_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitEncryptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).InitEncryption(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreService_InitEncryption_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).InitEncryption(ctx, req.(*InitEncryptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_RotateEncryption_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RotateEncryptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).RotateEncryption(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreService_RotateEncryption_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).RotateEncryption(ctx, req.(*RotateEncryptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_GrantAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GrantAccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).GrantAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreService_GrantAccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).GrantAccess(ctx, req.(*GrantAccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_RevokeAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeAccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).RevokeAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreService_RevokeAccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).RevokeAccess(ctx, req.(*RevokeAccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_ListAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).ListAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreService_ListAccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).ListAccess(ctx, req.(*ListAccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StoreService_ServiceDesc is the grpc.ServiceDesc for StoreService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StoreService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "zhiplugin.v1.StoreService",
	HandlerType: (*StoreServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Capabilities",
			Handler:    _StoreService_Capabilities_Handler,
		},
		{
			MethodName: "AuthMethods",
			Handler:    _StoreService_AuthMethods_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _StoreService_Login_Handler,
		},
		{
			MethodName: "ListTrees",
			Handler:    _StoreService_ListTrees_Handler,
		},
		{
			MethodName: "DeleteTree",
			Handler:    _StoreService_DeleteTree_Handler,
		},
		{
			MethodName: "GetValues",
			Handler:    _StoreService_GetValues_Handler,
		},
		{
			MethodName: "PutValues",
			Handler:    _StoreService_PutValues_Handler,
		},
		{
			MethodName: "DeleteValues",
			Handler:    _StoreService_DeleteValues_Handler,
		},
		{
			MethodName: "ListTreeVersions",
			Handler:    _StoreService_ListTreeVersions_Handler,
		},
		{
			MethodName: "GetTreeVersion",
			Handler:    _StoreService_GetTreeVersion_Handler,
		},
		{
			MethodName: "RollbackTree",
			Handler:    _StoreService_RollbackTree_Handler,
		},
		{
			MethodName: "DeleteTreeVersion",
			Handler:    _StoreService_DeleteTreeVersion_Handler,
		},
		{
			MethodName: "ListValueVersions",
			Handler:    _StoreService_ListValueVersions_Handler,
		},
		{
			MethodName: "GetValueVersion",
			Handler:    _StoreService_GetValueVersion_Handler,
		},
		{
			MethodName: "RollbackValue",
			Handler:    _StoreService_RollbackValue_Handler,
		},
		{
			MethodName: "DeleteValueVersion",
			Handler:    _StoreService_DeleteValueVersion_Handler,
		},
		{
			MethodName: "InitEncryption",
			Handler:    _StoreService_InitEncryption_Handler,
		},
		{
			MethodName: "RotateEncryption",
			Handler:    _StoreService_RotateEncryption_Handler,
		},
		{
			MethodName: "GrantAccess",
			Handler:    _StoreService_GrantAccess_Handler,
		},
		{
			MethodName: "RevokeAccess",
			Handler:    _StoreService_RevokeAccess_Handler,
		},
		{
			MethodName: "ListAccess",
			Handler:    _StoreService_ListAccess_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "zhiplugin/v1/store.proto",
}
