// Copyright 2025 Lukas Schmidt
// SPDX-License-Identifier: MIT

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: zhiplugin/v1/store.proto

package proto

import (
	proto "github.com/MrWong99/zhi/pkg/zhiplugin/config/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SaveRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The identifier for this configuration tree.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The full configuration tree to persist.
	Tree          []*proto.TreeEntry `protobuf:"bytes,2,rep,name=tree,proto3" json:"tree,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveRequest) Reset() {
	*x = SaveRequest{}
	mi := &file_zhiplugin_v1_store_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveRequest) ProtoMessage() {}

func (x *SaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zhiplugin_v1_store_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveRequest.ProtoReflect.Descriptor instead.
func (*SaveRequest) Descriptor() ([]byte, []int) {
	return file_zhiplugin_v1_store_proto_rawDescGZIP(), []int{0}
}

func (x *SaveRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SaveRequest) GetTree() []*proto.TreeEntry {
	if x != nil {
		return x.Tree
	}
	return nil
}

// SaveResponse is intentionally empty.
type SaveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveResponse) Reset() {
	*x = SaveResponse{}
	mi := &file_zhiplugin_v1_store_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveResponse) ProtoMessage() {}

func (x *SaveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zhiplugin_v1_store_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveResponse.ProtoReflect.Descriptor instead.
func (*SaveResponse) Descriptor() ([]byte, []int) {
	return file_zhiplugin_v1_store_proto_rawDescGZIP(), []int{1}
}

type LoadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadRequest) Reset() {
	*x = LoadRequest{}
	mi := &file_zhiplugin_v1_store_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadRequest) ProtoMessage() {}

func (x *LoadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zhiplugin_v1_store_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadRequest.ProtoReflect.Descriptor instead.
func (*LoadRequest) Descriptor() ([]byte, []int) {
	return file_zhiplugin_v1_store_proto_rawDescGZIP(), []int{2}
}

func (x *LoadRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type LoadResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Found bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	// The configuration tree entries. Empty when found is false.
	Tree          []*proto.TreeEntry `protobuf:"bytes,2,rep,name=tree,proto3" json:"tree,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadResponse) Reset() {
	*x = LoadResponse{}
	mi := &file_zhiplugin_v1_store_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadResponse) ProtoMessage() {}

func (x *LoadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zhiplugin_v1_store_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadResponse.ProtoReflect.Descriptor instead.
func (*LoadResponse) Descriptor() ([]byte, []int) {
	return file_zhiplugin_v1_store_proto_rawDescGZIP(), []int{3}
}

func (x *LoadResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *LoadResponse) GetTree() []*proto.TreeEntry {
	if x != nil {
		return x.Tree
	}
	return nil
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_zhiplugin_v1_store_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zhiplugin_v1_store_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_zhiplugin_v1_store_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// DeleteResponse is intentionally empty.
type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_zhiplugin_v1_store_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zhiplugin_v1_store_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_zhiplugin_v1_store_proto_rawDescGZIP(), []int{5}
}

// ListTreesRequest is intentionally empty.
type ListTreesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTreesRequest) Reset() {
	*x = ListTreesRequest{}
	mi := &file_zhiplugin_v1_store_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTreesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTreesRequest) ProtoMessage() {}

func (x *ListTreesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zhiplugin_v1_store_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTreesRequest.ProtoReflect.Descriptor instead.
func (*ListTreesRequest) Descriptor() ([]byte, []int) {
	return file_zhiplugin_v1_store_proto_rawDescGZIP(), []int{6}
}

type ListTreesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTreesResponse) Reset() {
	*x = ListTreesResponse{}
	mi := &file_zhiplugin_v1_store_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTreesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTreesResponse) ProtoMessage() {}

func (x *ListTreesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zhiplugin_v1_store_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTreesResponse.ProtoReflect.Descriptor instead.
func (*ListTreesResponse) Descriptor() ([]byte, []int) {
	return file_zhiplugin_v1_store_proto_rawDescGZIP(), []int{7}
}

func (x *ListTreesResponse) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

// SupportsVersioningRequest is intentionally empty.
type SupportsVersioningRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SupportsVersioningRequest) Reset() {
	*x = SupportsVersioningRequest{}
	mi := &file_zhiplugin_v1_store_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SupportsVersioningRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupportsVersioningRequest) ProtoMessage() {}

func (x *SupportsVersioningRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zhiplugin_v1_store_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SupportsVersioningRequest.ProtoReflect.Descriptor instead.
func (*SupportsVersioningRequest) Descriptor() ([]byte, []int) {
	return file_zhiplugin_v1_store_proto_rawDescGZIP(), []int{8}
}

type SupportsVersioningResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Supported     bool                   `protobuf:"varint,1,opt,name=supported,proto3" json:"supported,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SupportsVersioningResponse) Reset() {
	*x = SupportsVersioningResponse{}
	mi := &file_zhiplugin_v1_store_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SupportsVersioningResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupportsVersioningResponse) ProtoMessage() {}

func (x *SupportsVersioningResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zhiplugin_v1_store_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SupportsVersioningResponse.ProtoReflect.Descriptor instead.
func (*SupportsVersioningResponse) Descriptor() ([]byte, []int) {
	return file_zhiplugin_v1_store_proto_rawDescGZIP(), []int{9}
}

func (x *SupportsVersioningResponse) GetSupported() bool {
	if x != nil {
		return x.Supported
	}
	return false
}

type ListVersionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVersionsRequest) Reset() {
	*x = ListVersionsRequest{}
	mi := &file_zhiplugin_v1_store_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVersionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVersionsRequest) ProtoMessage() {}

func (x *ListVersionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zhiplugin_v1_store_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVersionsRequest.ProtoReflect.Descriptor instead.
func (*ListVersionsRequest) Descriptor() ([]byte, []int) {
	return file_zhiplugin_v1_store_proto_rawDescGZIP(), []int{10}
}

func (x *ListVersionsRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListVersionsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Version identifiers, ordered newest first.
	Versions      []string `protobuf:"bytes,1,rep,name=versions,proto3" json:"versions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVersionsResponse) Reset() {
	*x = ListVersionsResponse{}
	mi := &file_zhiplugin_v1_store_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVersionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVersionsResponse) ProtoMessage() {}

func (x *ListVersionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zhiplugin_v1_store_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVersionsResponse.ProtoReflect.Descriptor instead.
func (*ListVersionsResponse) Descriptor() ([]byte, []int) {
	return file_zhiplugin_v1_store_proto_rawDescGZIP(), []int{11}
}

func (x *ListVersionsResponse) GetVersions() []string {
	if x != nil {
		return x.Versions
	}
	return nil
}

type LoadVersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadVersionRequest) Reset() {
	*x = LoadVersionRequest{}
	mi := &file_zhiplugin_v1_store_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadVersionRequest) ProtoMessage() {}

func (x *LoadVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zhiplugin_v1_store_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadVersionRequest.ProtoReflect.Descriptor instead.
func (*LoadVersionRequest) Descriptor() ([]byte, []int) {
	return file_zhiplugin_v1_store_proto_rawDescGZIP(), []int{12}
}

func (x *LoadVersionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LoadVersionRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type LoadVersionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Found bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	// The configuration tree entries. Empty when found is false.
	Tree          []*proto.TreeEntry `protobuf:"bytes,2,rep,name=tree,proto3" json:"tree,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadVersionResponse) Reset() {
	*x = LoadVersionResponse{}
	mi := &file_zhiplugin_v1_store_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadVersionResponse) ProtoMessage() {}

func (x *LoadVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zhiplugin_v1_store_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadVersionResponse.ProtoReflect.Descriptor instead.
func (*LoadVersionResponse) Descriptor() ([]byte, []int) {
	return file_zhiplugin_v1_store_proto_rawDescGZIP(), []int{13}
}

func (x *LoadVersionResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *LoadVersionResponse) GetTree() []*proto.TreeEntry {
	if x != nil {
		return x.Tree
	}
	return nil
}

type DeleteVersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVersionRequest) Reset() {
	*x = DeleteVersionRequest{}
	mi := &file_zhiplugin_v1_store_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVersionRequest) ProtoMessage() {}

func (x *DeleteVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zhiplugin_v1_store_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVersionRequest.ProtoReflect.Descriptor instead.
func (*DeleteVersionRequest) Descriptor() ([]byte, []int) {
	return file_zhiplugin_v1_store_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteVersionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteVersionRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// DeleteVersionResponse is intentionally empty.
type DeleteVersionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVersionResponse) Reset() {
	*x = DeleteVersionResponse{}
	mi := &file_zhiplugin_v1_store_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVersionResponse) ProtoMessage() {}

func (x *DeleteVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zhiplugin_v1_store_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVersionResponse.ProtoReflect.Descriptor instead.
func (*DeleteVersionResponse) Descriptor() ([]byte, []int) {
	return file_zhiplugin_v1_store_proto_rawDescGZIP(), []int{15}
}

// EncryptionStatusRequest is intentionally empty.
type EncryptionStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncryptionStatusRequest) Reset() {
	*x = EncryptionStatusRequest{}
	mi := &file_zhiplugin_v1_store_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncryptionStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptionStatusRequest) ProtoMessage() {}

func (x *EncryptionStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zhiplugin_v1_store_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptionStatusRequest.ProtoReflect.Descriptor instead.
func (*EncryptionStatusRequest) Descriptor() ([]byte, []int) {
	return file_zhiplugin_v1_store_proto_rawDescGZIP(), []int{16}
}

type EncryptionStatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 0 = EncryptionNone, 1 = EncryptionSupported, 2 = EncryptionActive.
	Status        int32 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncryptionStatusResponse) Reset() {
	*x = EncryptionStatusResponse{}
	mi := &file_zhiplugin_v1_store_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncryptionStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptionStatusResponse) ProtoMessage() {}

func (x *EncryptionStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zhiplugin_v1_store_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptionStatusResponse.ProtoReflect.Descriptor instead.
func (*EncryptionStatusResponse) Descriptor() ([]byte, []int) {
	return file_zhiplugin_v1_store_proto_rawDescGZIP(), []int{17}
}

func (x *EncryptionStatusResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type InitEncryptionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The passphrase or key material to initialize encryption with.
	Passphrase    []byte `protobuf:"bytes,1,opt,name=passphrase,proto3" json:"passphrase,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitEncryptionRequest) Reset() {
	*x = InitEncryptionRequest{}
	mi := &file_zhiplugin_v1_store_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitEncryptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitEncryptionRequest) ProtoMessage() {}

func (x *InitEncryptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zhiplugin_v1_store_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitEncryptionRequest.ProtoReflect.Descriptor instead.
func (*InitEncryptionRequest) Descriptor() ([]byte, []int) {
	return file_zhiplugin_v1_store_proto_rawDescGZIP(), []int{18}
}

func (x *InitEncryptionRequest) GetPassphrase() []byte {
	if x != nil {
		return x.Passphrase
	}
	return nil
}

// InitEncryptionResponse is intentionally empty.
type InitEncryptionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitEncryptionResponse) Reset() {
	*x = InitEncryptionResponse{}
	mi := &file_zhiplugin_v1_store_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitEncryptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitEncryptionResponse) ProtoMessage() {}

func (x *InitEncryptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zhiplugin_v1_store_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitEncryptionResponse.ProtoReflect.Descriptor instead.
func (*InitEncryptionResponse) Descriptor() ([]byte, []int) {
	return file_zhiplugin_v1_store_proto_rawDescGZIP(), []int{19}
}

type RotateEncryptionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The current passphrase.
	OldPassphrase []byte `protobuf:"bytes,1,opt,name=old_passphrase,json=oldPassphrase,proto3" json:"old_passphrase,omitempty"`
	// The new passphrase to rotate to.
	NewPassphrase []byte `protobuf:"bytes,2,opt,name=new_passphrase,json=newPassphrase,proto3" json:"new_passphrase,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RotateEncryptionRequest) Reset() {
	*x = RotateEncryptionRequest{}
	mi := &file_zhiplugin_v1_store_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateEncryptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateEncryptionRequest) ProtoMessage() {}

func (x *RotateEncryptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zhiplugin_v1_store_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateEncryptionRequest.ProtoReflect.Descriptor instead.
func (*RotateEncryptionRequest) Descriptor() ([]byte, []int) {
	return file_zhiplugin_v1_store_proto_rawDescGZIP(), []int{20}
}

func (x *RotateEncryptionRequest) GetOldPassphrase() []byte {
	if x != nil {
		return x.OldPassphrase
	}
	return nil
}

func (x *RotateEncryptionRequest) GetNewPassphrase() []byte {
	if x != nil {
		return x.NewPassphrase
	}
	return nil
}

// RotateEncryptionResponse is intentionally empty.
type RotateEncryptionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RotateEncryptionResponse) Reset() {
	*x = RotateEncryptionResponse{}
	mi := &file_zhiplugin_v1_store_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateEncryptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateEncryptionResponse) ProtoMessage() {}

func (x *RotateEncryptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zhiplugin_v1_store_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateEncryptionResponse.ProtoReflect.Descriptor instead.
func (*RotateEncryptionResponse) Descriptor() ([]byte, []int) {
	return file_zhiplugin_v1_store_proto_rawDescGZIP(), []int{21}
}

var File_zhiplugin_v1_store_proto protoreflect.FileDescriptor

const file_zhiplugin_v1_store_proto_rawDesc = "" +
	"\n" +
	"\x18zhiplugin/v1/store.proto\x12\fzhiplugin.v1\x1a\x19zhiplugin/v1/config.proto\"J\n" +
	"\vSaveRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12+\n" +
	"\x04tree\x18\x02 \x03(\v2\x17.zhiplugin.v1.TreeEntryR\x04tree\"\x0e\n" +
	"\fSaveResponse\"\x1d\n" +
	"\vLoadRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"Q\n" +
	"\fLoadResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12+\n" +
	"\x04tree\x18\x02 \x03(\v2\x17.zhiplugin.v1.TreeEntryR\x04tree\"\x1f\n" +
	"\rDeleteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x10\n" +
	"\x0eDeleteResponse\"\x12\n" +
	"\x10ListTreesRequest\"%\n" +
	"\x11ListTreesResponse\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\"\x1b\n" +
	"\x19SupportsVersioningRequest\":\n" +
	"\x1aSupportsVersioningResponse\x12\x1c\n" +
	"\tsupported\x18\x01 \x01(\bR\tsupported\"%\n" +
	"\x13ListVersionsRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"2\n" +
	"\x14ListVersionsResponse\x12\x1a\n" +
	"\bversions\x18\x01 \x03(\tR\bversions\">\n" +
	"\x12LoadVersionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"X\n" +
	"\x13LoadVersionResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12+\n" +
	"\x04tree\x18\x02 \x03(\v2\x17.zhiplugin.v1.TreeEntryR\x04tree\"@\n" +
	"\x14DeleteVersionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"\x17\n" +
	"\x15DeleteVersionResponse\"\x19\n" +
	"\x17EncryptionStatusRequest\"2\n" +
	"\x18EncryptionStatusResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\"7\n" +
	"\x15InitEncryptionRequest\x12\x1e\n" +
	"\n" +
	"passphrase\x18\x01 \x01(\fR\n" +
	"passphrase\"\x18\n" +
	"\x16InitEncryptionResponse\"g\n" +
	"\x17RotateEncryptionRequest\x12%\n" +
	"\x0eold_passphrase\x18\x01 \x01(\fR\roldPassphrase\x12%\n" +
	"\x0enew_passphrase\x18\x02 \x01(\fR\rnewPassphrase\"\x1a\n" +
	"\x18RotateEncryptionResponse2\xb0\a\n" +
	"\fStoreService\x12=\n" +
	"\x04Save\x12\x19.zhiplugin.v1.SaveRequest\x1a\x1a.zhiplugin.v1.SaveResponse\x12=\n" +
	"\x04Load\x12\x19.zhiplugin.v1.LoadRequest\x1a\x1a.zhiplugin.v1.LoadResponse\x12C\n" +
	"\x06Delete\x12\x1b.zhiplugin.v1.DeleteRequest\x1a\x1c.zhiplugin.v1.DeleteResponse\x12L\n" +
	"\tListTrees\x12\x1e.zhiplugin.v1.ListTreesRequest\x1a\x1f.zhiplugin.v1.ListTreesResponse\x12g\n" +
	"\x12SupportsVersioning\x12'.zhiplugin.v1.SupportsVersioningRequest\x1a(.zhiplugin.v1.SupportsVersioningResponse\x12U\n" +
	"\fListVersions\x12!.zhiplugin.v1.ListVersionsRequest\x1a\".zhiplugin.v1.ListVersionsResponse\x12R\n" +
	"\vLoadVersion\x12 .zhiplugin.v1.LoadVersionRequest\x1a!.zhiplugin.v1.LoadVersionResponse\x12X\n" +
	"\rDeleteVersion\x12\".zhiplugin.v1.DeleteVersionRequest\x1a#.zhiplugin.v1.DeleteVersionResponse\x12a\n" +
	"\x10EncryptionStatus\x12%.zhiplugin.v1.EncryptionStatusRequest\x1a&.zhiplugin.v1.EncryptionStatusResponse\x12[\n" +
	"\x0eInitEncryption\x12#.zhiplugin.v1.InitEncryptionRequest\x1a$.zhiplugin.v1.InitEncryptionResponse\x12a\n" +
	"\x10RotateEncryption\x12%.zhiplugin.v1.RotateEncryptionRequest\x1a&.zhiplugin.v1.RotateEncryptionResponseB3Z1github.com/MrWong99/zhi/pkg/zhiplugin/store/protob\x06proto3"

var (
	file_zhiplugin_v1_store_proto_rawDescOnce sync.Once
	file_zhiplugin_v1_store_proto_rawDescData []byte
)

func file_zhiplugin_v1_store_proto_rawDescGZIP() []byte {
	file_zhiplugin_v1_store_proto_rawDescOnce.Do(func() {
		file_zhiplugin_v1_store_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_zhiplugin_v1_store_proto_rawDesc), len(file_zhiplugin_v1_store_proto_rawDesc)))
	})
	return file_zhiplugin_v1_store_proto_rawDescData
}

var file_zhiplugin_v1_store_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_zhiplugin_v1_store_proto_goTypes = []any{
	(*SaveRequest)(nil),                // 0: zhiplugin.v1.SaveRequest
	(*SaveResponse)(nil),               // 1: zhiplugin.v1.SaveResponse
	(*LoadRequest)(nil),                // 2: zhiplugin.v1.LoadRequest
	(*LoadResponse)(nil),               // 3: zhiplugin.v1.LoadResponse
	(*DeleteRequest)(nil),              // 4: zhiplugin.v1.DeleteRequest
	(*DeleteResponse)(nil),             // 5: zhiplugin.v1.DeleteResponse
	(*ListTreesRequest)(nil),           // 6: zhiplugin.v1.ListTreesRequest
	(*ListTreesResponse)(nil),          // 7: zhiplugin.v1.ListTreesResponse
	(*SupportsVersioningRequest)(nil),  // 8: zhiplugin.v1.SupportsVersioningRequest
	(*SupportsVersioningResponse)(nil), // 9: zhiplugin.v1.SupportsVersioningResponse
	(*ListVersionsRequest)(nil),        // 10: zhiplugin.v1.ListVersionsRequest
	(*ListVersionsResponse)(nil),       // 11: zhiplugin.v1.ListVersionsResponse
	(*LoadVersionRequest)(nil),         // 12: zhiplugin.v1.LoadVersionRequest
	(*LoadVersionResponse)(nil),        // 13: zhiplugin.v1.LoadVersionResponse
	(*DeleteVersionRequest)(nil),       // 14: zhiplugin.v1.DeleteVersionRequest
	(*DeleteVersionResponse)(nil),      // 15: zhiplugin.v1.DeleteVersionResponse
	(*EncryptionStatusRequest)(nil),    // 16: zhiplugin.v1.EncryptionStatusRequest
	(*EncryptionStatusResponse)(nil),   // 17: zhiplugin.v1.EncryptionStatusResponse
	(*InitEncryptionRequest)(nil),      // 18: zhiplugin.v1.InitEncryptionRequest
	(*InitEncryptionResponse)(nil),     // 19: zhiplugin.v1.InitEncryptionResponse
	(*RotateEncryptionRequest)(nil),    // 20: zhiplugin.v1.RotateEncryptionRequest
	(*RotateEncryptionResponse)(nil),   // 21: zhiplugin.v1.RotateEncryptionResponse
	(*proto.TreeEntry)(nil),            // 22: zhiplugin.v1.TreeEntry
}
var file_zhiplugin_v1_store_proto_depIdxs = []int32{
	22, // 0: zhiplugin.v1.SaveRequest.tree:type_name -> zhiplugin.v1.TreeEntry
	22, // 1: zhiplugin.v1.LoadResponse.tree:type_name -> zhiplugin.v1.TreeEntry
	22, // 2: zhiplugin.v1.LoadVersionResponse.tree:type_name -> zhiplugin.v1.TreeEntry
	0,  // 3: zhiplugin.v1.StoreService.Save:input_type -> zhiplugin.v1.SaveRequest
	2,  // 4: zhiplugin.v1.StoreService.Load:input_type -> zhiplugin.v1.LoadRequest
	4,  // 5: zhiplugin.v1.StoreService.Delete:input_type -> zhiplugin.v1.DeleteRequest
	6,  // 6: zhiplugin.v1.StoreService.ListTrees:input_type -> zhiplugin.v1.ListTreesRequest
	8,  // 7: zhiplugin.v1.StoreService.SupportsVersioning:input_type -> zhiplugin.v1.SupportsVersioningRequest
	10, // 8: zhiplugin.v1.StoreService.ListVersions:input_type -> zhiplugin.v1.ListVersionsRequest
	12, // 9: zhiplugin.v1.StoreService.LoadVersion:input_type -> zhiplugin.v1.LoadVersionRequest
	14, // 10: zhiplugin.v1.StoreService.DeleteVersion:input_type -> zhiplugin.v1.DeleteVersionRequest
	16, // 11: zhiplugin.v1.StoreService.EncryptionStatus:input_type -> zhiplugin.v1.EncryptionStatusRequest
	18, // 12: zhiplugin.v1.StoreService.InitEncryption:input_type -> zhiplugin.v1.InitEncryptionRequest
	20, // 13: zhiplugin.v1.StoreService.RotateEncryption:input_type -> zhiplugin.v1.RotateEncryptionRequest
	1,  // 14: zhiplugin.v1.StoreService.Save:output_type -> zhiplugin.v1.SaveResponse
	3,  // 15: zhiplugin.v1.StoreService.Load:output_type -> zhiplugin.v1.LoadResponse
	5,  // 16: zhiplugin.v1.StoreService.Delete:output_type -> zhiplugin.v1.DeleteResponse
	7,  // 17: zhiplugin.v1.StoreService.ListTrees:output_type -> zhiplugin.v1.ListTreesResponse
	9,  // 18: zhiplugin.v1.StoreService.SupportsVersioning:output_type -> zhiplugin.v1.SupportsVersioningResponse
	11, // 19: zhiplugin.v1.StoreService.ListVersions:output_type -> zhiplugin.v1.ListVersionsResponse
	13, // 20: zhiplugin.v1.StoreService.LoadVersion:output_type -> zhiplugin.v1.LoadVersionResponse
	15, // 21: zhiplugin.v1.StoreService.DeleteVersion:output_type -> zhiplugin.v1.DeleteVersionResponse
	17, // 22: zhiplugin.v1.StoreService.EncryptionStatus:output_type -> zhiplugin.v1.EncryptionStatusResponse
	19, // 23: zhiplugin.v1.StoreService.InitEncryption:output_type -> zhiplugin.v1.InitEncryptionResponse
	21, // 24: zhiplugin.v1.StoreService.RotateEncryption:output_type -> zhiplugin.v1.RotateEncryptionResponse
	14, // [14:25] is the sub-list for method output_type
	3,  // [3:14] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_zhiplugin_v1_store_proto_init() }
func file_zhiplugin_v1_store_proto_init() {
	if File_zhiplugin_v1_store_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_zhiplugin_v1_store_proto_rawDesc), len(file_zhiplugin_v1_store_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_zhiplugin_v1_store_proto_goTypes,
		DependencyIndexes: file_zhiplugin_v1_store_proto_depIdxs,
		MessageInfos:      file_zhiplugin_v1_store_proto_msgTypes,
	}.Build()
	File_zhiplugin_v1_store_proto = out.File
	file_zhiplugin_v1_store_proto_goTypes = nil
	file_zhiplugin_v1_store_proto_depIdxs = nil
}
