// Copyright 2025 Lukas Schmidt
// SPDX-License-Identifier: MIT

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.5
// source: zhiplugin/v1/store.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StoreService_Save_FullMethodName               = "/zhiplugin.v1.StoreService/Save"
	StoreService_Load_FullMethodName               = "/zhiplugin.v1.StoreService/Load"
	StoreService_Delete_FullMethodName             = "/zhiplugin.v1.StoreService/Delete"
	StoreService_ListTrees_FullMethodName          = "/zhiplugin.v1.StoreService/ListTrees"
	StoreService_SupportsVersioning_FullMethodName = "/zhiplugin.v1.StoreService/SupportsVersioning"
	StoreService_ListVersions_FullMethodName       = "/zhiplugin.v1.StoreService/ListVersions"
	StoreService_LoadVersion_FullMethodName        = "/zhiplugin.v1.StoreService/LoadVersion"
	StoreService_DeleteVersion_FullMethodName      = "/zhiplugin.v1.StoreService/DeleteVersion"
	StoreService_EncryptionStatus_FullMethodName   = "/zhiplugin.v1.StoreService/EncryptionStatus"
	StoreService_InitEncryption_FullMethodName     = "/zhiplugin.v1.StoreService/InitEncryption"
	StoreService_RotateEncryption_FullMethodName   = "/zhiplugin.v1.StoreService/RotateEncryption"
)

// StoreServiceClient is the client API for StoreService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// StoreService is the gRPC interface every zhi store plugin must implement.
// Store plugins persist, retrieve, and delete configuration trees.
type StoreServiceClient interface {
	// Save persists a configuration tree under the given ID.
	// If versioning is supported, this creates a new version.
	Save(ctx context.Context, in *SaveRequest, opts ...grpc.CallOption) (*SaveResponse, error)
	// Load retrieves the latest version of the configuration tree with the
	// given ID.
	Load(ctx context.Context, in *LoadRequest, opts ...grpc.CallOption) (*LoadResponse, error)
	// Delete removes the configuration tree and all its versions.
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	// ListTrees returns all stored tree IDs.
	ListTrees(ctx context.Context, in *ListTreesRequest, opts ...grpc.CallOption) (*ListTreesResponse, error)
	// SupportsVersioning reports whether this store keeps older versions of
	// trees.
	SupportsVersioning(ctx context.Context, in *SupportsVersioningRequest, opts ...grpc.CallOption) (*SupportsVersioningResponse, error)
	// ListVersions returns version identifiers for a given tree ID, ordered
	// newest first. Returns an error if versioning is not supported.
	ListVersions(ctx context.Context, in *ListVersionsRequest, opts ...grpc.CallOption) (*ListVersionsResponse, error)
	// LoadVersion retrieves a specific version of the configuration tree.
	// Returns an error if versioning is not supported.
	LoadVersion(ctx context.Context, in *LoadVersionRequest, opts ...grpc.CallOption) (*LoadVersionResponse, error)
	// DeleteVersion permanently removes a single version of a configuration
	// tree. Returns an error if versioning is not supported.
	DeleteVersion(ctx context.Context, in *DeleteVersionRequest, opts ...grpc.CallOption) (*DeleteVersionResponse, error)
	// EncryptionStatus reports the current encryption state of the store.
	EncryptionStatus(ctx context.Context, in *EncryptionStatusRequest, opts ...grpc.CallOption) (*EncryptionStatusResponse, error)
	// InitEncryption initializes encryption for the store with the given
	// passphrase. Returns an error if encryption is not supported or is
	// already active.
	InitEncryption(ctx context.Context, in *InitEncryptionRequest, opts ...grpc.CallOption) (*InitEncryptionResponse, error)
	// RotateEncryption re-encrypts all stored data with a new passphrase.
	// Returns an error if encryption is not supported or not active.
	RotateEncryption(ctx context.Context, in *RotateEncryptionRequest, opts ...grpc.CallOption) (*RotateEncryptionResponse, error)
}

type storeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStoreServiceClient(cc grpc.ClientConnInterface) StoreServiceClient {
	return &storeServiceClient{cc}
}

func (c *storeServiceClient) Save(ctx context.Context, in *SaveRequest, opts ...grpc.CallOption) (*SaveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveResponse)
	err := c.cc.Invoke(ctx, StoreService_Save_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) Load(ctx context.Context, in *LoadRequest, opts ...grpc.CallOption) (*LoadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoadResponse)
	err := c.cc.Invoke(ctx, StoreService_Load_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, StoreService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) ListTrees(ctx context.Context, in *ListTreesRequest, opts ...grpc.CallOption) (*ListTreesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTreesResponse)
	err := c.cc.Invoke(ctx, StoreService_ListTrees_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) SupportsVersioning(ctx context.Context, in *SupportsVersioningRequest, opts ...grpc.CallOption) (*SupportsVersioningResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SupportsVersioningResponse)
	err := c.cc.Invoke(ctx, StoreService_SupportsVersioning_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) ListVersions(ctx context.Context, in *ListVersionsRequest, opts ...grpc.CallOption) (*ListVersionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListVersionsResponse)
	err := c.cc.Invoke(ctx, StoreService_ListVersions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) LoadVersion(ctx context.Context, in *LoadVersionRequest, opts ...grpc.CallOption) (*LoadVersionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoadVersionResponse)
	err := c.cc.Invoke(ctx, StoreService_LoadVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) DeleteVersion(ctx context.Context, in *DeleteVersionRequest, opts ...grpc.CallOption) (*DeleteVersionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteVersionResponse)
	err := c.cc.Invoke(ctx, StoreService_DeleteVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) EncryptionStatus(ctx context.Context, in *EncryptionStatusRequest, opts ...grpc.CallOption) (*EncryptionStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EncryptionStatusResponse)
	err := c.cc.Invoke(ctx, StoreService_EncryptionStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) InitEncryption(ctx context.Context, in *InitEncryptionRequest, opts ...grpc.CallOption) (*InitEncryptionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitEncryptionResponse)
	err := c.cc.Invoke(ctx, StoreService_InitEncryption_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) RotateEncryption(ctx context.Context, in *RotateEncryptionRequest, opts ...grpc.CallOption) (*RotateEncryptionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RotateEncryptionResponse)
	err := c.cc.Invoke(ctx, StoreService_RotateEncryption_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StoreServiceServer is the server API for StoreService service.
// All implementations must embed UnimplementedStoreServiceServer
// for forward compatibility.
//
// StoreService is the gRPC interface every zhi store plugin must implement.
// Store plugins persist, retrieve, and delete configuration trees.
type StoreServiceServer interface {
	// Save persists a configuration tree under the given ID.
	// If versioning is supported, this creates a new version.
	Save(context.Context, *SaveRequest) (*SaveResponse, error)
	// Load retrieves the latest version of the configuration tree with the
	// given ID.
	Load(context.Context, *LoadRequest) (*LoadResponse, error)
	// Delete removes the configuration tree and all its versions.
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
	// ListTrees returns all stored tree IDs.
	ListTrees(context.Context, *ListTreesRequest) (*ListTreesResponse, error)
	// SupportsVersioning reports whether this store keeps older versions of
	// trees.
	SupportsVersioning(context.Context, *SupportsVersioningRequest) (*SupportsVersioningResponse, error)
	// ListVersions returns version identifiers for a given tree ID, ordered
	// newest first. Returns an error if versioning is not supported.
	ListVersions(context.Context, *ListVersionsRequest) (*ListVersionsResponse, error)
	// LoadVersion retrieves a specific version of the configuration tree.
	// Returns an error if versioning is not supported.
	LoadVersion(context.Context, *LoadVersionRequest) (*LoadVersionResponse, error)
	// DeleteVersion permanently removes a single version of a configuration
	// tree. Returns an error if versioning is not supported.
	DeleteVersion(context.Context, *DeleteVersionRequest) (*DeleteVersionResponse, error)
	// EncryptionStatus reports the current encryption state of the store.
	EncryptionStatus(context.Context, *EncryptionStatusRequest) (*EncryptionStatusResponse, error)
	// InitEncryption initializes encryption for the store with the given
	// passphrase. Returns an error if encryption is not supported or is
	// already active.
	InitEncryption(context.Context, *InitEncryptionRequest) (*InitEncryptionResponse, error)
	// RotateEncryption re-encrypts all stored data with a new passphrase.
	// Returns an error if encryption is not supported or not active.
	RotateEncryption(context.Context, *RotateEncryptionRequest) (*RotateEncryptionResponse, error)
	mustEmbedUnimplementedStoreServiceServer()
}

// UnimplementedStoreServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStoreServiceServer struct{}

func (UnimplementedStoreServiceServer) Save(context.Context, *SaveRequest) (*SaveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Save not implemented")
}
func (UnimplementedStoreServiceServer) Load(context.Context, *LoadRequest) (*LoadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Load not implemented")
}
func (UnimplementedStoreServiceServer) Delete(context.Context, *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedStoreServiceServer) ListTrees(context.Context, *ListTreesRequest) (*ListTreesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTrees not implemented")
}
func (UnimplementedStoreServiceServer) SupportsVersioning(context.Context, *SupportsVersioningRequest) (*SupportsVersioningResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SupportsVersioning not implemented")
}
func (UnimplementedStoreServiceServer) ListVersions(context.Context, *ListVersionsRequest) (*ListVersionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListVersions not implemented")
}
func (UnimplementedStoreServiceServer) LoadVersion(context.Context, *LoadVersionRequest) (*LoadVersionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LoadVersion not implemented")
}
func (UnimplementedStoreServiceServer) DeleteVersion(context.Context, *DeleteVersionRequest) (*DeleteVersionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteVersion not implemented")
}
func (UnimplementedStoreServiceServer) EncryptionStatus(context.Context, *EncryptionStatusRequest) (*EncryptionStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EncryptionStatus not implemented")
}
func (UnimplementedStoreServiceServer) InitEncryption(context.Context, *InitEncryptionRequest) (*InitEncryptionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InitEncryption not implemented")
}
func (UnimplementedStoreServiceServer) RotateEncryption(context.Context, *RotateEncryptionRequest) (*RotateEncryptionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RotateEncryption not implemented")
}
func (UnimplementedStoreServiceServer) mustEmbedUnimplementedStoreServiceServer() {}
func (UnimplementedStoreServiceServer) testEmbeddedByValue()                      {}

// UnsafeStoreServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StoreServiceServer will
// result in compilation errors.
type UnsafeStoreServiceServer interface {
	mustEmbedUnimplementedStoreServiceServer()
}

func RegisterStoreServiceServer(s grpc.ServiceRegistrar, srv StoreServiceServer) {
	// If the following call panics, it indicates UnimplementedStoreServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StoreService_ServiceDesc, srv)
}

func _StoreService_Save_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).Save(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreService_Save_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).Save(ctx, req.(*SaveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_Load_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).Load(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreService_Load_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).Load(ctx, req.(*LoadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_ListTrees_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTreesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).ListTrees(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreService_ListTrees_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).ListTrees(ctx, req.(*ListTreesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_SupportsVersioning_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SupportsVersioningRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).SupportsVersioning(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreService_SupportsVersioning_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).SupportsVersioning(ctx, req.(*SupportsVersioningRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_ListVersions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListVersionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).ListVersions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreService_ListVersions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).ListVersions(ctx, req.(*ListVersionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_LoadVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).LoadVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreService_LoadVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).LoadVersion(ctx, req.(*LoadVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_DeleteVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).DeleteVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreService_DeleteVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).DeleteVersion(ctx, req.(*DeleteVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_EncryptionStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EncryptionStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).EncryptionStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreService_EncryptionStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).EncryptionStatus(ctx, req.(*EncryptionStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_InitEncryption_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitEncryptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).InitEncryption(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreService_InitEncryption_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).InitEncryption(ctx, req.(*InitEncryptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_RotateEncryption_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RotateEncryptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).RotateEncryption(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreService_RotateEncryption_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).RotateEncryption(ctx, req.(*RotateEncryptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StoreService_ServiceDesc is the grpc.ServiceDesc for StoreService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StoreService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "zhiplugin.v1.StoreService",
	HandlerType: (*StoreServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Save",
			Handler:    _StoreService_Save_Handler,
		},
		{
			MethodName: "Load",
			Handler:    _StoreService_Load_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _StoreService_Delete_Handler,
		},
		{
			MethodName: "ListTrees",
			Handler:    _StoreService_ListTrees_Handler,
		},
		{
			MethodName: "SupportsVersioning",
			Handler:    _StoreService_SupportsVersioning_Handler,
		},
		{
			MethodName: "ListVersions",
			Handler:    _StoreService_ListVersions_Handler,
		},
		{
			MethodName: "LoadVersion",
			Handler:    _StoreService_LoadVersion_Handler,
		},
		{
			MethodName: "DeleteVersion",
			Handler:    _StoreService_DeleteVersion_Handler,
		},
		{
			MethodName: "EncryptionStatus",
			Handler:    _StoreService_EncryptionStatus_Handler,
		},
		{
			MethodName: "InitEncryption",
			Handler:    _StoreService_InitEncryption_Handler,
		},
		{
			MethodName: "RotateEncryption",
			Handler:    _StoreService_RotateEncryption_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "zhiplugin/v1/store.proto",
}
