// Copyright 2025 Lukas Schmidt
// SPDX-License-Identifier: MIT

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: transform.proto

package proto

import (
	proto "github.com/MrWong99/zhi/pkg/zhiplugin/config/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TransformRequest carries the full configuration tree for transformation.
type TransformRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A snapshot of the full merged configuration tree.
	Tree          []*proto.TreeEntry `protobuf:"bytes,1,rep,name=tree,proto3" json:"tree,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransformRequest) Reset() {
	*x = TransformRequest{}
	mi := &file_transform_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransformRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransformRequest) ProtoMessage() {}

func (x *TransformRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transform_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransformRequest.ProtoReflect.Descriptor instead.
func (*TransformRequest) Descriptor() ([]byte, []int) {
	return file_transform_proto_rawDescGZIP(), []int{0}
}

func (x *TransformRequest) GetTree() []*proto.TreeEntry {
	if x != nil {
		return x.Tree
	}
	return nil
}

// TransformResponse carries the transformed configuration tree back to the
// host.
type TransformResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The modified configuration tree.
	Tree          []*proto.TreeEntry `protobuf:"bytes,1,rep,name=tree,proto3" json:"tree,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransformResponse) Reset() {
	*x = TransformResponse{}
	mi := &file_transform_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransformResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransformResponse) ProtoMessage() {}

func (x *TransformResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transform_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransformResponse.ProtoReflect.Descriptor instead.
func (*TransformResponse) Descriptor() ([]byte, []int) {
	return file_transform_proto_rawDescGZIP(), []int{1}
}

func (x *TransformResponse) GetTree() []*proto.TreeEntry {
	if x != nil {
		return x.Tree
	}
	return nil
}

// ValidatePolicyRequest is intentionally empty.
type ValidatePolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidatePolicyRequest) Reset() {
	*x = ValidatePolicyRequest{}
	mi := &file_transform_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidatePolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidatePolicyRequest) ProtoMessage() {}

func (x *ValidatePolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transform_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidatePolicyRequest.ProtoReflect.Descriptor instead.
func (*ValidatePolicyRequest) Descriptor() ([]byte, []int) {
	return file_transform_proto_rawDescGZIP(), []int{2}
}

type ValidatePolicyResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 0 = ValidateBeforeTransform, 1 = ValidateAfterTransform,
	// 2 = ValidateBoth.
	Policy        int32 `protobuf:"varint,1,opt,name=policy,proto3" json:"policy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidatePolicyResponse) Reset() {
	*x = ValidatePolicyResponse{}
	mi := &file_transform_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidatePolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidatePolicyResponse) ProtoMessage() {}

func (x *ValidatePolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transform_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidatePolicyResponse.ProtoReflect.Descriptor instead.
func (*ValidatePolicyResponse) Descriptor() ([]byte, []int) {
	return file_transform_proto_rawDescGZIP(), []int{3}
}

func (x *ValidatePolicyResponse) GetPolicy() int32 {
	if x != nil {
		return x.Policy
	}
	return 0
}

var File_transform_proto protoreflect.FileDescriptor

const file_transform_proto_rawDesc = "" +
	"\n" +
	"\x0ftransform.proto\x12\fzhiplugin.v1\x1a\fconfig.proto\"?\n" +
	"\x10TransformRequest\x12+\n" +
	"\x04tree\x18\x01 \x03(\v2\x17.zhiplugin.v1.TreeEntryR\x04tree\"@\n" +
	"\x11TransformResponse\x12+\n" +
	"\x04tree\x18\x01 \x03(\v2\x17.zhiplugin.v1.TreeEntryR\x04tree\"\x17\n" +
	"\x15ValidatePolicyRequest\"0\n" +
	"\x16ValidatePolicyResponse\x12\x16\n" +
	"\x06policy\x18\x01 \x01(\x05R\x06policy2\x8f\x02\n" +
	"\x10TransformService\x12P\n" +
	"\rBeforeDisplay\x12\x1e.zhiplugin.v1.TransformRequest\x1a\x1f.zhiplugin.v1.TransformResponse\x12L\n" +
	"\tAfterSave\x12\x1e.zhiplugin.v1.TransformRequest\x1a\x1f.zhiplugin.v1.TransformResponse\x12[\n" +
	"\x0eValidatePolicy\x12#.zhiplugin.v1.ValidatePolicyRequest\x1a$.zhiplugin.v1.ValidatePolicyResponseB7Z5github.com/MrWong99/zhi/pkg/zhiplugin/transform/protob\x06proto3"

var (
	file_transform_proto_rawDescOnce sync.Once
	file_transform_proto_rawDescData []byte
)

func file_transform_proto_rawDescGZIP() []byte {
	file_transform_proto_rawDescOnce.Do(func() {
		file_transform_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transform_proto_rawDesc), len(file_transform_proto_rawDesc)))
	})
	return file_transform_proto_rawDescData
}

var file_transform_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_transform_proto_goTypes = []any{
	(*TransformRequest)(nil),       // 0: zhiplugin.v1.TransformRequest
	(*TransformResponse)(nil),      // 1: zhiplugin.v1.TransformResponse
	(*ValidatePolicyRequest)(nil),  // 2: zhiplugin.v1.ValidatePolicyRequest
	(*ValidatePolicyResponse)(nil), // 3: zhiplugin.v1.ValidatePolicyResponse
	(*proto.TreeEntry)(nil),        // 4: zhiplugin.v1.TreeEntry
}
var file_transform_proto_depIdxs = []int32{
	4, // 0: zhiplugin.v1.TransformRequest.tree:type_name -> zhiplugin.v1.TreeEntry
	4, // 1: zhiplugin.v1.TransformResponse.tree:type_name -> zhiplugin.v1.TreeEntry
	0, // 2: zhiplugin.v1.TransformService.BeforeDisplay:input_type -> zhiplugin.v1.TransformRequest
	0, // 3: zhiplugin.v1.TransformService.AfterSave:input_type -> zhiplugin.v1.TransformRequest
	2, // 4: zhiplugin.v1.TransformService.ValidatePolicy:input_type -> zhiplugin.v1.ValidatePolicyRequest
	1, // 5: zhiplugin.v1.TransformService.BeforeDisplay:output_type -> zhiplugin.v1.TransformResponse
	1, // 6: zhiplugin.v1.TransformService.AfterSave:output_type -> zhiplugin.v1.TransformResponse
	3, // 7: zhiplugin.v1.TransformService.ValidatePolicy:output_type -> zhiplugin.v1.ValidatePolicyResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_transform_proto_init() }
func file_transform_proto_init() {
	if File_transform_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transform_proto_rawDesc), len(file_transform_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_transform_proto_goTypes,
		DependencyIndexes: file_transform_proto_depIdxs,
		MessageInfos:      file_transform_proto_msgTypes,
	}.Build()
	File_transform_proto = out.File
	file_transform_proto_goTypes = nil
	file_transform_proto_depIdxs = nil
}
