// Copyright 2025 Lukas Schmidt
// SPDX-License-Identifier: MIT

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.33.5
// source: zhiplugin/v1/transform.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TransformService_BeforeDisplay_FullMethodName  = "/zhiplugin.v1.TransformService/BeforeDisplay"
	TransformService_AfterSave_FullMethodName      = "/zhiplugin.v1.TransformService/AfterSave"
	TransformService_ValidatePolicy_FullMethodName = "/zhiplugin.v1.TransformService/ValidatePolicy"
)

// TransformServiceClient is the client API for TransformService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TransformService is the gRPC interface every zhi transform plugin must
// implement.
type TransformServiceClient interface {
	// BeforeDisplay transforms the configuration tree before values are
	// displayed in the UI.
	BeforeDisplay(ctx context.Context, in *BeforeDisplayRequest, opts ...grpc.CallOption) (*BeforeDisplayResponse, error)
	// AfterSave transforms the configuration tree after the UI stores
	// updates.
	AfterSave(ctx context.Context, in *AfterSaveRequest, opts ...grpc.CallOption) (*AfterSaveResponse, error)
	// ValidatePolicy reports when config-plugin validations should run
	// relative to the transformation.
	ValidatePolicy(ctx context.Context, in *ValidatePolicyRequest, opts ...grpc.CallOption) (*ValidatePolicyResponse, error)
}

type transformServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTransformServiceClient(cc grpc.ClientConnInterface) TransformServiceClient {
	return &transformServiceClient{cc}
}

func (c *transformServiceClient) BeforeDisplay(ctx context.Context, in *BeforeDisplayRequest, opts ...grpc.CallOption) (*BeforeDisplayResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BeforeDisplayResponse)
	err := c.cc.Invoke(ctx, TransformService_BeforeDisplay_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transformServiceClient) AfterSave(ctx context.Context, in *AfterSaveRequest, opts ...grpc.CallOption) (*AfterSaveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AfterSaveResponse)
	err := c.cc.Invoke(ctx, TransformService_AfterSave_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transformServiceClient) ValidatePolicy(ctx context.Context, in *ValidatePolicyRequest, opts ...grpc.CallOption) (*ValidatePolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidatePolicyResponse)
	err := c.cc.Invoke(ctx, TransformService_ValidatePolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TransformServiceServer is the server API for TransformService service.
// All implementations must embed UnimplementedTransformServiceServer
// for forward compatibility.
//
// TransformService is the gRPC interface every zhi transform plugin must
// implement.
type TransformServiceServer interface {
	// BeforeDisplay transforms the configuration tree before values are
	// displayed in the UI.
	BeforeDisplay(context.Context, *BeforeDisplayRequest) (*BeforeDisplayResponse, error)
	// AfterSave transforms the configuration tree after the UI stores
	// updates.
	AfterSave(context.Context, *AfterSaveRequest) (*AfterSaveResponse, error)
	// ValidatePolicy reports when config-plugin validations should run
	// relative to the transformation.
	ValidatePolicy(context.Context, *ValidatePolicyRequest) (*ValidatePolicyResponse, error)
	mustEmbedUnimplementedTransformServiceServer()
}

// UnimplementedTransformServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTransformServiceServer struct{}

func (UnimplementedTransformServiceServer) BeforeDisplay(context.Context, *BeforeDisplayRequest) (*BeforeDisplayResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BeforeDisplay not implemented")
}
func (UnimplementedTransformServiceServer) AfterSave(context.Context, *AfterSaveRequest) (*AfterSaveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AfterSave not implemented")
}
func (UnimplementedTransformServiceServer) ValidatePolicy(context.Context, *ValidatePolicyRequest) (*ValidatePolicyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidatePolicy not implemented")
}
func (UnimplementedTransformServiceServer) mustEmbedUnimplementedTransformServiceServer() {}
func (UnimplementedTransformServiceServer) testEmbeddedByValue()                          {}

// UnsafeTransformServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TransformServiceServer will
// result in compilation errors.
type UnsafeTransformServiceServer interface {
	mustEmbedUnimplementedTransformServiceServer()
}

func RegisterTransformServiceServer(s grpc.ServiceRegistrar, srv TransformServiceServer) {
	// If the following call panics, it indicates UnimplementedTransformServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TransformService_ServiceDesc, srv)
}

func _TransformService_BeforeDisplay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BeforeDisplayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransformServiceServer).BeforeDisplay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransformService_BeforeDisplay_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransformServiceServer).BeforeDisplay(ctx, req.(*BeforeDisplayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransformService_AfterSave_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AfterSaveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransformServiceServer).AfterSave(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransformService_AfterSave_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransformServiceServer).AfterSave(ctx, req.(*AfterSaveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransformService_ValidatePolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidatePolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransformServiceServer).ValidatePolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransformService_ValidatePolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransformServiceServer).ValidatePolicy(ctx, req.(*ValidatePolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TransformService_ServiceDesc is the grpc.ServiceDesc for TransformService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TransformService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "zhiplugin.v1.TransformService",
	HandlerType: (*TransformServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BeforeDisplay",
			Handler:    _TransformService_BeforeDisplay_Handler,
		},
		{
			MethodName: "AfterSave",
			Handler:    _TransformService_AfterSave_Handler,
		},
		{
			MethodName: "ValidatePolicy",
			Handler:    _TransformService_ValidatePolicy_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "zhiplugin/v1/transform.proto",
}
