// Copyright 2025 Lukas Schmidt
// SPDX-License-Identifier: MIT

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: zhiplugin/v1/transform.proto

package proto

import (
	proto "github.com/MrWong99/zhi/pkg/zhiplugin/config/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BeforeDisplayRequest carries the full configuration tree for the
// BeforeDisplay transformation.
type BeforeDisplayRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A snapshot of the full merged configuration tree.
	Tree          []*proto.TreeEntry `protobuf:"bytes,1,rep,name=tree,proto3" json:"tree,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeforeDisplayRequest) Reset() {
	*x = BeforeDisplayRequest{}
	mi := &file_zhiplugin_v1_transform_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeforeDisplayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeforeDisplayRequest) ProtoMessage() {}

func (x *BeforeDisplayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zhiplugin_v1_transform_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeforeDisplayRequest.ProtoReflect.Descriptor instead.
func (*BeforeDisplayRequest) Descriptor() ([]byte, []int) {
	return file_zhiplugin_v1_transform_proto_rawDescGZIP(), []int{0}
}

func (x *BeforeDisplayRequest) GetTree() []*proto.TreeEntry {
	if x != nil {
		return x.Tree
	}
	return nil
}

// BeforeDisplayResponse carries the transformed configuration tree back to
// the host after the BeforeDisplay transformation.
type BeforeDisplayResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The modified configuration tree.
	Tree          []*proto.TreeEntry `protobuf:"bytes,1,rep,name=tree,proto3" json:"tree,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeforeDisplayResponse) Reset() {
	*x = BeforeDisplayResponse{}
	mi := &file_zhiplugin_v1_transform_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeforeDisplayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeforeDisplayResponse) ProtoMessage() {}

func (x *BeforeDisplayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zhiplugin_v1_transform_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeforeDisplayResponse.ProtoReflect.Descriptor instead.
func (*BeforeDisplayResponse) Descriptor() ([]byte, []int) {
	return file_zhiplugin_v1_transform_proto_rawDescGZIP(), []int{1}
}

func (x *BeforeDisplayResponse) GetTree() []*proto.TreeEntry {
	if x != nil {
		return x.Tree
	}
	return nil
}

// AfterSaveRequest carries the full configuration tree for the AfterSave
// transformation.
type AfterSaveRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A snapshot of the full merged configuration tree.
	Tree          []*proto.TreeEntry `protobuf:"bytes,1,rep,name=tree,proto3" json:"tree,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AfterSaveRequest) Reset() {
	*x = AfterSaveRequest{}
	mi := &file_zhiplugin_v1_transform_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AfterSaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AfterSaveRequest) ProtoMessage() {}

func (x *AfterSaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zhiplugin_v1_transform_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AfterSaveRequest.ProtoReflect.Descriptor instead.
func (*AfterSaveRequest) Descriptor() ([]byte, []int) {
	return file_zhiplugin_v1_transform_proto_rawDescGZIP(), []int{2}
}

func (x *AfterSaveRequest) GetTree() []*proto.TreeEntry {
	if x != nil {
		return x.Tree
	}
	return nil
}

// AfterSaveResponse carries the transformed configuration tree back to the
// host after the AfterSave transformation.
type AfterSaveResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The modified configuration tree.
	Tree          []*proto.TreeEntry `protobuf:"bytes,1,rep,name=tree,proto3" json:"tree,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AfterSaveResponse) Reset() {
	*x = AfterSaveResponse{}
	mi := &file_zhiplugin_v1_transform_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AfterSaveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AfterSaveResponse) ProtoMessage() {}

func (x *AfterSaveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zhiplugin_v1_transform_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AfterSaveResponse.ProtoReflect.Descriptor instead.
func (*AfterSaveResponse) Descriptor() ([]byte, []int) {
	return file_zhiplugin_v1_transform_proto_rawDescGZIP(), []int{3}
}

func (x *AfterSaveResponse) GetTree() []*proto.TreeEntry {
	if x != nil {
		return x.Tree
	}
	return nil
}

// ValidatePolicyRequest is intentionally empty.
type ValidatePolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidatePolicyRequest) Reset() {
	*x = ValidatePolicyRequest{}
	mi := &file_zhiplugin_v1_transform_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidatePolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidatePolicyRequest) ProtoMessage() {}

func (x *ValidatePolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zhiplugin_v1_transform_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidatePolicyRequest.ProtoReflect.Descriptor instead.
func (*ValidatePolicyRequest) Descriptor() ([]byte, []int) {
	return file_zhiplugin_v1_transform_proto_rawDescGZIP(), []int{4}
}

type ValidatePolicyResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 0 = ValidateBeforeTransform, 1 = ValidateAfterTransform,
	// 2 = ValidateBoth.
	Policy        int32 `protobuf:"varint,1,opt,name=policy,proto3" json:"policy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidatePolicyResponse) Reset() {
	*x = ValidatePolicyResponse{}
	mi := &file_zhiplugin_v1_transform_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidatePolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidatePolicyResponse) ProtoMessage() {}

func (x *ValidatePolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zhiplugin_v1_transform_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidatePolicyResponse.ProtoReflect.Descriptor instead.
func (*ValidatePolicyResponse) Descriptor() ([]byte, []int) {
	return file_zhiplugin_v1_transform_proto_rawDescGZIP(), []int{5}
}

func (x *ValidatePolicyResponse) GetPolicy() int32 {
	if x != nil {
		return x.Policy
	}
	return 0
}

var File_zhiplugin_v1_transform_proto protoreflect.FileDescriptor

const file_zhiplugin_v1_transform_proto_rawDesc = "" +
	"\n" +
	"\x1czhiplugin/v1/transform.proto\x12\fzhiplugin.v1\x1a\x19zhiplugin/v1/config.proto\"C\n" +
	"\x14BeforeDisplayRequest\x12+\n" +
	"\x04tree\x18\x01 \x03(\v2\x17.zhiplugin.v1.TreeEntryR\x04tree\"D\n" +
	"\x15BeforeDisplayResponse\x12+\n" +
	"\x04tree\x18\x01 \x03(\v2\x17.zhiplugin.v1.TreeEntryR\x04tree\"?\n" +
	"\x10AfterSaveRequest\x12+\n" +
	"\x04tree\x18\x01 \x03(\v2\x17.zhiplugin.v1.TreeEntryR\x04tree\"@\n" +
	"\x11AfterSaveResponse\x12+\n" +
	"\x04tree\x18\x01 \x03(\v2\x17.zhiplugin.v1.TreeEntryR\x04tree\"\x17\n" +
	"\x15ValidatePolicyRequest\"0\n" +
	"\x16ValidatePolicyResponse\x12\x16\n" +
	"\x06policy\x18\x01 \x01(\x05R\x06policy2\x97\x02\n" +
	"\x10TransformService\x12X\n" +
	"\rBeforeDisplay\x12\".zhiplugin.v1.BeforeDisplayRequest\x1a#.zhiplugin.v1.BeforeDisplayResponse\x12L\n" +
	"\tAfterSave\x12\x1e.zhiplugin.v1.AfterSaveRequest\x1a\x1f.zhiplugin.v1.AfterSaveResponse\x12[\n" +
	"\x0eValidatePolicy\x12#.zhiplugin.v1.ValidatePolicyRequest\x1a$.zhiplugin.v1.ValidatePolicyResponseB7Z5github.com/MrWong99/zhi/pkg/zhiplugin/transform/protob\x06proto3"

var (
	file_zhiplugin_v1_transform_proto_rawDescOnce sync.Once
	file_zhiplugin_v1_transform_proto_rawDescData []byte
)

func file_zhiplugin_v1_transform_proto_rawDescGZIP() []byte {
	file_zhiplugin_v1_transform_proto_rawDescOnce.Do(func() {
		file_zhiplugin_v1_transform_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_zhiplugin_v1_transform_proto_rawDesc), len(file_zhiplugin_v1_transform_proto_rawDesc)))
	})
	return file_zhiplugin_v1_transform_proto_rawDescData
}

var file_zhiplugin_v1_transform_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_zhiplugin_v1_transform_proto_goTypes = []any{
	(*BeforeDisplayRequest)(nil),   // 0: zhiplugin.v1.BeforeDisplayRequest
	(*BeforeDisplayResponse)(nil),  // 1: zhiplugin.v1.BeforeDisplayResponse
	(*AfterSaveRequest)(nil),       // 2: zhiplugin.v1.AfterSaveRequest
	(*AfterSaveResponse)(nil),      // 3: zhiplugin.v1.AfterSaveResponse
	(*ValidatePolicyRequest)(nil),  // 4: zhiplugin.v1.ValidatePolicyRequest
	(*ValidatePolicyResponse)(nil), // 5: zhiplugin.v1.ValidatePolicyResponse
	(*proto.TreeEntry)(nil),        // 6: zhiplugin.v1.TreeEntry
}
var file_zhiplugin_v1_transform_proto_depIdxs = []int32{
	6, // 0: zhiplugin.v1.BeforeDisplayRequest.tree:type_name -> zhiplugin.v1.TreeEntry
	6, // 1: zhiplugin.v1.BeforeDisplayResponse.tree:type_name -> zhiplugin.v1.TreeEntry
	6, // 2: zhiplugin.v1.AfterSaveRequest.tree:type_name -> zhiplugin.v1.TreeEntry
	6, // 3: zhiplugin.v1.AfterSaveResponse.tree:type_name -> zhiplugin.v1.TreeEntry
	0, // 4: zhiplugin.v1.TransformService.BeforeDisplay:input_type -> zhiplugin.v1.BeforeDisplayRequest
	2, // 5: zhiplugin.v1.TransformService.AfterSave:input_type -> zhiplugin.v1.AfterSaveRequest
	4, // 6: zhiplugin.v1.TransformService.ValidatePolicy:input_type -> zhiplugin.v1.ValidatePolicyRequest
	1, // 7: zhiplugin.v1.TransformService.BeforeDisplay:output_type -> zhiplugin.v1.BeforeDisplayResponse
	3, // 8: zhiplugin.v1.TransformService.AfterSave:output_type -> zhiplugin.v1.AfterSaveResponse
	5, // 9: zhiplugin.v1.TransformService.ValidatePolicy:output_type -> zhiplugin.v1.ValidatePolicyResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_zhiplugin_v1_transform_proto_init() }
func file_zhiplugin_v1_transform_proto_init() {
	if File_zhiplugin_v1_transform_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_zhiplugin_v1_transform_proto_rawDesc), len(file_zhiplugin_v1_transform_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_zhiplugin_v1_transform_proto_goTypes,
		DependencyIndexes: file_zhiplugin_v1_transform_proto_depIdxs,
		MessageInfos:      file_zhiplugin_v1_transform_proto_msgTypes,
	}.Build()
	File_zhiplugin_v1_transform_proto = out.File
	file_zhiplugin_v1_transform_proto_goTypes = nil
	file_zhiplugin_v1_transform_proto_depIdxs = nil
}
