# Copyright 2025 Lukas Schmidt
# SPDX-License-Identifier: MIT

version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: zhi
    main: ./cmd/zhi/
    binary: zhi
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

  - id: zhi-marketplace
    main: ./cmd/zhi-marketplace/
    binary: zhi-marketplace
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

  - id: zhi-mirror
    main: ./cmd/zhi-mirror/
    binary: zhi-mirror
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

archives:
  - id: zhi
    builds:
      - zhi
    formats:
      - tar.gz
    name_template: "zhi_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

  - id: zhi-marketplace
    builds:
      - zhi-marketplace
    formats:
      - tar.gz
    name_template: "zhi-marketplace_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

  - id: zhi-mirror
    builds:
      - zhi-mirror
    formats:
      - tar.gz
    name_template: "zhi-mirror_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  use: github

release:
  github:
    owner: MrWong99
    name: zhi
  draft: false
  prerelease: auto
  name_template: "Version {{ .Version }}"
  header: |
    # zhi Release {{ .Version }} - {{ .Date }}
  footer: |
    ## Plugin OCI installs

    ```sh
    # "Production" plugins
    zhi plugin install oci://ghcr.io/mrwong99/zhi/zhi-store-vault:{{ .Tag }}
    zhi plugin install oci://ghcr.io/mrwong99/zhi/zhi-ui-webui:{{ .Tag }}

    # Examples
    zhi plugin install oci://ghcr.io/mrwong99/zhi/zhi-config-pokedex:{{ .Tag }}
    zhi plugin install oci://ghcr.io/mrwong99/zhi/zhi-store-json:{{ .Tag }}
    zhi plugin install oci://ghcr.io/mrwong99/zhi/zhi-store-memory:{{ .Tag }}
    zhi plugin install oci://ghcr.io/mrwong99/zhi/zhi-transform-pokedex:{{ .Tag }}
    zhi plugin install oci://ghcr.io/mrwong99/zhi/zhi-ui-httpapi:{{ .Tag }}
    ```

    ## Workspace OCI installs

    ```sh
    zhi workspace install ghcr.io/mrwong99/zhi/zhi-workspace-vault:{{ .Tag }}
    zhi workspace install ghcr.io/mrwong99/zhi/zhi-workspace-zhi:{{ .Tag }}
    ```
