// Copyright 2025 Lukas Schmidt
// SPDX-License-Identifier: MIT

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: zhiplugin/v1/config.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ListRequest is intentionally empty.
type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_zhiplugin_v1_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zhiplugin_v1_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_zhiplugin_v1_config_proto_rawDescGZIP(), []int{0}
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Paths         []string               `protobuf:"bytes,1,rep,name=paths,proto3" json:"paths,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_zhiplugin_v1_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zhiplugin_v1_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_zhiplugin_v1_config_proto_rawDescGZIP(), []int{1}
}

func (x *ListResponse) GetPaths() []string {
	if x != nil {
		return x.Paths
	}
	return nil
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_zhiplugin_v1_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zhiplugin_v1_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_zhiplugin_v1_config_proto_rawDescGZIP(), []int{2}
}

func (x *GetRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type GetResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Found bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	// JSON-encoded configuration value. Empty when found is false.
	ValueJson []byte `protobuf:"bytes,2,opt,name=value_json,json=valueJson,proto3" json:"value_json,omitempty"`
	// JSON-encoded metadata. May be empty.
	MetadataJson  []byte `protobuf:"bytes,3,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_zhiplugin_v1_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zhiplugin_v1_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_zhiplugin_v1_config_proto_rawDescGZIP(), []int{3}
}

func (x *GetResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetResponse) GetValueJson() []byte {
	if x != nil {
		return x.ValueJson
	}
	return nil
}

func (x *GetResponse) GetMetadataJson() []byte {
	if x != nil {
		return x.MetadataJson
	}
	return nil
}

type SetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	ValueJson     []byte                 `protobuf:"bytes,2,opt,name=value_json,json=valueJson,proto3" json:"value_json,omitempty"`
	MetadataJson  []byte                 `protobuf:"bytes,3,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRequest) Reset() {
	*x = SetRequest{}
	mi := &file_zhiplugin_v1_config_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRequest) ProtoMessage() {}

func (x *SetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zhiplugin_v1_config_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRequest.ProtoReflect.Descriptor instead.
func (*SetRequest) Descriptor() ([]byte, []int) {
	return file_zhiplugin_v1_config_proto_rawDescGZIP(), []int{4}
}

func (x *SetRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *SetRequest) GetValueJson() []byte {
	if x != nil {
		return x.ValueJson
	}
	return nil
}

func (x *SetRequest) GetMetadataJson() []byte {
	if x != nil {
		return x.MetadataJson
	}
	return nil
}

// SetResponse is intentionally empty.
type SetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetResponse) Reset() {
	*x = SetResponse{}
	mi := &file_zhiplugin_v1_config_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetResponse) ProtoMessage() {}

func (x *SetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zhiplugin_v1_config_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetResponse.ProtoReflect.Descriptor instead.
func (*SetResponse) Descriptor() ([]byte, []int) {
	return file_zhiplugin_v1_config_proto_rawDescGZIP(), []int{5}
}

// TreeEntry is a single value in the configuration tree snapshot sent during
// validation.
type TreeEntry struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Path         string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	ValueJson    []byte                 `protobuf:"bytes,2,opt,name=value_json,json=valueJson,proto3" json:"value_json,omitempty"`
	MetadataJson []byte                 `protobuf:"bytes,3,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`
	// Optional version identifier. Populated by store plugins on reads and
	// used for optimistic locking (check-and-set) on writes.
	Version       string `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TreeEntry) Reset() {
	*x = TreeEntry{}
	mi := &file_zhiplugin_v1_config_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TreeEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TreeEntry) ProtoMessage() {}

func (x *TreeEntry) ProtoReflect() protoreflect.Message {
	mi := &file_zhiplugin_v1_config_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TreeEntry.ProtoReflect.Descriptor instead.
func (*TreeEntry) Descriptor() ([]byte, []int) {
	return file_zhiplugin_v1_config_proto_rawDescGZIP(), []int{6}
}

func (x *TreeEntry) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *TreeEntry) GetValueJson() []byte {
	if x != nil {
		return x.ValueJson
	}
	return nil
}

func (x *TreeEntry) GetMetadataJson() []byte {
	if x != nil {
		return x.MetadataJson
	}
	return nil
}

func (x *TreeEntry) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type ValidateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The path of the value to validate.
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// A snapshot of the full merged configuration tree so that cross-value
	// validation is possible.
	Tree          []*TreeEntry `protobuf:"bytes,2,rep,name=tree,proto3" json:"tree,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateRequest) Reset() {
	*x = ValidateRequest{}
	mi := &file_zhiplugin_v1_config_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateRequest) ProtoMessage() {}

func (x *ValidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zhiplugin_v1_config_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateRequest.ProtoReflect.Descriptor instead.
func (*ValidateRequest) Descriptor() ([]byte, []int) {
	return file_zhiplugin_v1_config_proto_rawDescGZIP(), []int{7}
}

func (x *ValidateRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ValidateRequest) GetTree() []*TreeEntry {
	if x != nil {
		return x.Tree
	}
	return nil
}

type ValidationResultMsg struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 0 = Info, 1 = Warning, 2 = Blocking.
	Severity int32  `protobuf:"varint,1,opt,name=severity,proto3" json:"severity,omitempty"`
	Message  string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// JSON-encoded metadata. May be empty.
	MetadataJson  []byte `protobuf:"bytes,3,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidationResultMsg) Reset() {
	*x = ValidationResultMsg{}
	mi := &file_zhiplugin_v1_config_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidationResultMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationResultMsg) ProtoMessage() {}

func (x *ValidationResultMsg) ProtoReflect() protoreflect.Message {
	mi := &file_zhiplugin_v1_config_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidationResultMsg.ProtoReflect.Descriptor instead.
func (*ValidationResultMsg) Descriptor() ([]byte, []int) {
	return file_zhiplugin_v1_config_proto_rawDescGZIP(), []int{8}
}

func (x *ValidationResultMsg) GetSeverity() int32 {
	if x != nil {
		return x.Severity
	}
	return 0
}

func (x *ValidationResultMsg) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ValidationResultMsg) GetMetadataJson() []byte {
	if x != nil {
		return x.MetadataJson
	}
	return nil
}

type ValidateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*ValidationResultMsg `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateResponse) Reset() {
	*x = ValidateResponse{}
	mi := &file_zhiplugin_v1_config_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateResponse) ProtoMessage() {}

func (x *ValidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zhiplugin_v1_config_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateResponse.ProtoReflect.Descriptor instead.
func (*ValidateResponse) Descriptor() ([]byte, []int) {
	return file_zhiplugin_v1_config_proto_rawDescGZIP(), []int{9}
}

func (x *ValidateResponse) GetResults() []*ValidationResultMsg {
	if x != nil {
		return x.Results
	}
	return nil
}

var File_zhiplugin_v1_config_proto protoreflect.FileDescriptor

const file_zhiplugin_v1_config_proto_rawDesc = "" +
	"\n" +
	"\x19zhiplugin/v1/config.proto\x12\fzhiplugin.v1\"\r\n" +
	"\vListRequest\"$\n" +
	"\fListResponse\x12\x14\n" +
	"\x05paths\x18\x01 \x03(\tR\x05paths\" \n" +
	"\n" +
	"GetRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"g\n" +
	"\vGetResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12\x1d\n" +
	"\n" +
	"value_json\x18\x02 \x01(\fR\tvalueJson\x12#\n" +
	"\rmetadata_json\x18\x03 \x01(\fR\fmetadataJson\"d\n" +
	"\n" +
	"SetRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1d\n" +
	"\n" +
	"value_json\x18\x02 \x01(\fR\tvalueJson\x12#\n" +
	"\rmetadata_json\x18\x03 \x01(\fR\fmetadataJson\"\r\n" +
	"\vSetResponse\"}\n" +
	"\tTreeEntry\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1d\n" +
	"\n" +
	"value_json\x18\x02 \x01(\fR\tvalueJson\x12#\n" +
	"\rmetadata_json\x18\x03 \x01(\fR\fmetadataJson\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\"R\n" +
	"\x0fValidateRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12+\n" +
	"\x04tree\x18\x02 \x03(\v2\x17.zhiplugin.v1.TreeEntryR\x04tree\"p\n" +
	"\x13ValidationResultMsg\x12\x1a\n" +
	"\bseverity\x18\x01 \x01(\x05R\bseverity\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12#\n" +
	"\rmetadata_json\x18\x03 \x01(\fR\fmetadataJson\"O\n" +
	"\x10ValidateResponse\x12;\n" +
	"\aresults\x18\x01 \x03(\v2!.zhiplugin.v1.ValidationResultMsgR\aresults2\x91\x02\n" +
	"\rConfigService\x12=\n" +
	"\x04List\x12\x19.zhiplugin.v1.ListRequest\x1a\x1a.zhiplugin.v1.ListResponse\x12:\n" +
	"\x03Get\x12\x18.zhiplugin.v1.GetRequest\x1a\x19.zhiplugin.v1.GetResponse\x12:\n" +
	"\x03Set\x12\x18.zhiplugin.v1.SetRequest\x1a\x19.zhiplugin.v1.SetResponse\x12I\n" +
	"\bValidate\x12\x1d.zhiplugin.v1.ValidateRequest\x1a\x1e.zhiplugin.v1.ValidateResponseB4Z2github.com/MrWong99/zhi/pkg/zhiplugin/config/protob\x06proto3"

var (
	file_zhiplugin_v1_config_proto_rawDescOnce sync.Once
	file_zhiplugin_v1_config_proto_rawDescData []byte
)

func file_zhiplugin_v1_config_proto_rawDescGZIP() []byte {
	file_zhiplugin_v1_config_proto_rawDescOnce.Do(func() {
		file_zhiplugin_v1_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_zhiplugin_v1_config_proto_rawDesc), len(file_zhiplugin_v1_config_proto_rawDesc)))
	})
	return file_zhiplugin_v1_config_proto_rawDescData
}

var file_zhiplugin_v1_config_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_zhiplugin_v1_config_proto_goTypes = []any{
	(*ListRequest)(nil),         // 0: zhiplugin.v1.ListRequest
	(*ListResponse)(nil),        // 1: zhiplugin.v1.ListResponse
	(*GetRequest)(nil),          // 2: zhiplugin.v1.GetRequest
	(*GetResponse)(nil),         // 3: zhiplugin.v1.GetResponse
	(*SetRequest)(nil),          // 4: zhiplugin.v1.SetRequest
	(*SetResponse)(nil),         // 5: zhiplugin.v1.SetResponse
	(*TreeEntry)(nil),           // 6: zhiplugin.v1.TreeEntry
	(*ValidateRequest)(nil),     // 7: zhiplugin.v1.ValidateRequest
	(*ValidationResultMsg)(nil), // 8: zhiplugin.v1.ValidationResultMsg
	(*ValidateResponse)(nil),    // 9: zhiplugin.v1.ValidateResponse
}
var file_zhiplugin_v1_config_proto_depIdxs = []int32{
	6, // 0: zhiplugin.v1.ValidateRequest.tree:type_name -> zhiplugin.v1.TreeEntry
	8, // 1: zhiplugin.v1.ValidateResponse.results:type_name -> zhiplugin.v1.ValidationResultMsg
	0, // 2: zhiplugin.v1.ConfigService.List:input_type -> zhiplugin.v1.ListRequest
	2, // 3: zhiplugin.v1.ConfigService.Get:input_type -> zhiplugin.v1.GetRequest
	4, // 4: zhiplugin.v1.ConfigService.Set:input_type -> zhiplugin.v1.SetRequest
	7, // 5: zhiplugin.v1.ConfigService.Validate:input_type -> zhiplugin.v1.ValidateRequest
	1, // 6: zhiplugin.v1.ConfigService.List:output_type -> zhiplugin.v1.ListResponse
	3, // 7: zhiplugin.v1.ConfigService.Get:output_type -> zhiplugin.v1.GetResponse
	5, // 8: zhiplugin.v1.ConfigService.Set:output_type -> zhiplugin.v1.SetResponse
	9, // 9: zhiplugin.v1.ConfigService.Validate:output_type -> zhiplugin.v1.ValidateResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_zhiplugin_v1_config_proto_init() }
func file_zhiplugin_v1_config_proto_init() {
	if File_zhiplugin_v1_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_zhiplugin_v1_config_proto_rawDesc), len(file_zhiplugin_v1_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_zhiplugin_v1_config_proto_goTypes,
		DependencyIndexes: file_zhiplugin_v1_config_proto_depIdxs,
		MessageInfos:      file_zhiplugin_v1_config_proto_msgTypes,
	}.Build()
	File_zhiplugin_v1_config_proto = out.File
	file_zhiplugin_v1_config_proto_goTypes = nil
	file_zhiplugin_v1_config_proto_depIdxs = nil
}
