name: zhi
version: 1.1.0
description: This zhi deployment can be used to deploy a zhi-mirror and zhi-marketplace.
author: MrWong99
license: MIT
dependencies:
  - ref: oci://ghcr.io/mrwong99/zhi/zhi-store-vault:v1.1.0
    type: store
    optional: false
tools:
  - name: docker
    version: 29.2.1
  - name: docker compose
    version: 5.0.2
keywords:
  - zhi
  - mirror
  - marketplace
  - deployment
  - docker
