// Copyright 2025 Lukas Schmidt
// SPDX-License-Identifier: MIT

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: zhiplugin/v1/ui.proto

package proto

import (
	proto "github.com/MrWong99/zhi/pkg/zhiplugin/config/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RunRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The GRPCBroker server ID hosting the UIControllerService.
	ControllerBrokerId uint32 `protobuf:"varint,1,opt,name=controller_broker_id,json=controllerBrokerId,proto3" json:"controller_broker_id,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RunRequest) Reset() {
	*x = RunRequest{}
	mi := &file_zhiplugin_v1_ui_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunRequest) ProtoMessage() {}

func (x *RunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zhiplugin_v1_ui_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunRequest.ProtoReflect.Descriptor instead.
func (*RunRequest) Descriptor() ([]byte, []int) {
	return file_zhiplugin_v1_ui_proto_rawDescGZIP(), []int{0}
}

func (x *RunRequest) GetControllerBrokerId() uint32 {
	if x != nil {
		return x.ControllerBrokerId
	}
	return 0
}

// RunResponse is intentionally empty; Run blocks until the UI exits.
type RunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunResponse) Reset() {
	*x = RunResponse{}
	mi := &file_zhiplugin_v1_ui_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunResponse) ProtoMessage() {}

func (x *RunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zhiplugin_v1_ui_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunResponse.ProtoReflect.Descriptor instead.
func (*RunResponse) Descriptor() ([]byte, []int) {
	return file_zhiplugin_v1_ui_proto_rawDescGZIP(), []int{1}
}

// CapabilitiesRequest is intentionally empty.
type CapabilitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilitiesRequest) Reset() {
	*x = CapabilitiesRequest{}
	mi := &file_zhiplugin_v1_ui_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilitiesRequest) ProtoMessage() {}

func (x *CapabilitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zhiplugin_v1_ui_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilitiesRequest.ProtoReflect.Descriptor instead.
func (*CapabilitiesRequest) Descriptor() ([]byte, []int) {
	return file_zhiplugin_v1_ui_proto_rawDescGZIP(), []int{2}
}

type CapabilitiesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether this UI requires direct TTY access (must run as a builtin plugin).
	RequiresTty   bool `protobuf:"varint,1,opt,name=requires_tty,json=requiresTty,proto3" json:"requires_tty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilitiesResponse) Reset() {
	*x = CapabilitiesResponse{}
	mi := &file_zhiplugin_v1_ui_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilitiesResponse) ProtoMessage() {}

func (x *CapabilitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zhiplugin_v1_ui_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilitiesResponse.ProtoReflect.Descriptor instead.
func (*CapabilitiesResponse) Descriptor() ([]byte, []int) {
	return file_zhiplugin_v1_ui_proto_rawDescGZIP(), []int{3}
}

func (x *CapabilitiesResponse) GetRequiresTty() bool {
	if x != nil {
		return x.RequiresTty
	}
	return false
}

// CtrlLoadTreeRequest is intentionally empty.
type CtrlLoadTreeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CtrlLoadTreeRequest) Reset() {
	*x = CtrlLoadTreeRequest{}
	mi := &file_zhiplugin_v1_ui_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CtrlLoadTreeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CtrlLoadTreeRequest) ProtoMessage() {}

func (x *CtrlLoadTreeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zhiplugin_v1_ui_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CtrlLoadTreeRequest.ProtoReflect.Descriptor instead.
func (*CtrlLoadTreeRequest) Descriptor() ([]byte, []int) {
	return file_zhiplugin_v1_ui_proto_rawDescGZIP(), []int{4}
}

type CtrlLoadTreeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tree          []*proto.TreeEntry     `protobuf:"bytes,1,rep,name=tree,proto3" json:"tree,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CtrlLoadTreeResponse) Reset() {
	*x = CtrlLoadTreeResponse{}
	mi := &file_zhiplugin_v1_ui_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CtrlLoadTreeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CtrlLoadTreeResponse) ProtoMessage() {}

func (x *CtrlLoadTreeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zhiplugin_v1_ui_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CtrlLoadTreeResponse.ProtoReflect.Descriptor instead.
func (*CtrlLoadTreeResponse) Descriptor() ([]byte, []int) {
	return file_zhiplugin_v1_ui_proto_rawDescGZIP(), []int{5}
}

func (x *CtrlLoadTreeResponse) GetTree() []*proto.TreeEntry {
	if x != nil {
		return x.Tree
	}
	return nil
}

type CtrlSetValueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	ValueJson     []byte                 `protobuf:"bytes,2,opt,name=value_json,json=valueJson,proto3" json:"value_json,omitempty"`
	MetadataJson  []byte                 `protobuf:"bytes,3,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CtrlSetValueRequest) Reset() {
	*x = CtrlSetValueRequest{}
	mi := &file_zhiplugin_v1_ui_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CtrlSetValueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CtrlSetValueRequest) ProtoMessage() {}

func (x *CtrlSetValueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zhiplugin_v1_ui_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CtrlSetValueRequest.ProtoReflect.Descriptor instead.
func (*CtrlSetValueRequest) Descriptor() ([]byte, []int) {
	return file_zhiplugin_v1_ui_proto_rawDescGZIP(), []int{6}
}

func (x *CtrlSetValueRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *CtrlSetValueRequest) GetValueJson() []byte {
	if x != nil {
		return x.ValueJson
	}
	return nil
}

func (x *CtrlSetValueRequest) GetMetadataJson() []byte {
	if x != nil {
		return x.MetadataJson
	}
	return nil
}

// CtrlSetValueResponse is intentionally empty.
type CtrlSetValueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CtrlSetValueResponse) Reset() {
	*x = CtrlSetValueResponse{}
	mi := &file_zhiplugin_v1_ui_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CtrlSetValueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CtrlSetValueResponse) ProtoMessage() {}

func (x *CtrlSetValueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zhiplugin_v1_ui_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CtrlSetValueResponse.ProtoReflect.Descriptor instead.
func (*CtrlSetValueResponse) Descriptor() ([]byte, []int) {
	return file_zhiplugin_v1_ui_proto_rawDescGZIP(), []int{7}
}

// CtrlValidateRequest is intentionally empty.
type CtrlValidateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CtrlValidateRequest) Reset() {
	*x = CtrlValidateRequest{}
	mi := &file_zhiplugin_v1_ui_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CtrlValidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CtrlValidateRequest) ProtoMessage() {}

func (x *CtrlValidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zhiplugin_v1_ui_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CtrlValidateRequest.ProtoReflect.Descriptor instead.
func (*CtrlValidateRequest) Descriptor() ([]byte, []int) {
	return file_zhiplugin_v1_ui_proto_rawDescGZIP(), []int{8}
}

type CtrlValidateResponse struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Results       []*proto.ValidationResultMsg `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CtrlValidateResponse) Reset() {
	*x = CtrlValidateResponse{}
	mi := &file_zhiplugin_v1_ui_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CtrlValidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CtrlValidateResponse) ProtoMessage() {}

func (x *CtrlValidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zhiplugin_v1_ui_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CtrlValidateResponse.ProtoReflect.Descriptor instead.
func (*CtrlValidateResponse) Descriptor() ([]byte, []int) {
	return file_zhiplugin_v1_ui_proto_rawDescGZIP(), []int{9}
}

func (x *CtrlValidateResponse) GetResults() []*proto.ValidationResultMsg {
	if x != nil {
		return x.Results
	}
	return nil
}

type CtrlSaveTreeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CtrlSaveTreeRequest) Reset() {
	*x = CtrlSaveTreeRequest{}
	mi := &file_zhiplugin_v1_ui_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CtrlSaveTreeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CtrlSaveTreeRequest) ProtoMessage() {}

func (x *CtrlSaveTreeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zhiplugin_v1_ui_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CtrlSaveTreeRequest.ProtoReflect.Descriptor instead.
func (*CtrlSaveTreeRequest) Descriptor() ([]byte, []int) {
	return file_zhiplugin_v1_ui_proto_rawDescGZIP(), []int{10}
}

func (x *CtrlSaveTreeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// CtrlSaveTreeResponse is intentionally empty.
type CtrlSaveTreeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CtrlSaveTreeResponse) Reset() {
	*x = CtrlSaveTreeResponse{}
	mi := &file_zhiplugin_v1_ui_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CtrlSaveTreeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CtrlSaveTreeResponse) ProtoMessage() {}

func (x *CtrlSaveTreeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zhiplugin_v1_ui_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CtrlSaveTreeResponse.ProtoReflect.Descriptor instead.
func (*CtrlSaveTreeResponse) Descriptor() ([]byte, []int) {
	return file_zhiplugin_v1_ui_proto_rawDescGZIP(), []int{11}
}

// CtrlExportTemplatesRequest is intentionally empty.
type CtrlExportTemplatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CtrlExportTemplatesRequest) Reset() {
	*x = CtrlExportTemplatesRequest{}
	mi := &file_zhiplugin_v1_ui_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CtrlExportTemplatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CtrlExportTemplatesRequest) ProtoMessage() {}

func (x *CtrlExportTemplatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zhiplugin_v1_ui_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CtrlExportTemplatesRequest.ProtoReflect.Descriptor instead.
func (*CtrlExportTemplatesRequest) Descriptor() ([]byte, []int) {
	return file_zhiplugin_v1_ui_proto_rawDescGZIP(), []int{12}
}

type CtrlExportTemplateMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Template      string                 `protobuf:"bytes,2,opt,name=template,proto3" json:"template,omitempty"`
	Format        string                 `protobuf:"bytes,3,opt,name=format,proto3" json:"format,omitempty"`
	Output        string                 `protobuf:"bytes,4,opt,name=output,proto3" json:"output,omitempty"`
	Prefix        string                 `protobuf:"bytes,5,opt,name=prefix,proto3" json:"prefix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CtrlExportTemplateMsg) Reset() {
	*x = CtrlExportTemplateMsg{}
	mi := &file_zhiplugin_v1_ui_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CtrlExportTemplateMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CtrlExportTemplateMsg) ProtoMessage() {}

func (x *CtrlExportTemplateMsg) ProtoReflect() protoreflect.Message {
	mi := &file_zhiplugin_v1_ui_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CtrlExportTemplateMsg.ProtoReflect.Descriptor instead.
func (*CtrlExportTemplateMsg) Descriptor() ([]byte, []int) {
	return file_zhiplugin_v1_ui_proto_rawDescGZIP(), []int{13}
}

func (x *CtrlExportTemplateMsg) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CtrlExportTemplateMsg) GetTemplate() string {
	if x != nil {
		return x.Template
	}
	return ""
}

func (x *CtrlExportTemplateMsg) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *CtrlExportTemplateMsg) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *CtrlExportTemplateMsg) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

type CtrlExportTemplatesResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Templates     []*CtrlExportTemplateMsg `protobuf:"bytes,1,rep,name=templates,proto3" json:"templates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CtrlExportTemplatesResponse) Reset() {
	*x = CtrlExportTemplatesResponse{}
	mi := &file_zhiplugin_v1_ui_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CtrlExportTemplatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CtrlExportTemplatesResponse) ProtoMessage() {}

func (x *CtrlExportTemplatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zhiplugin_v1_ui_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CtrlExportTemplatesResponse.ProtoReflect.Descriptor instead.
func (*CtrlExportTemplatesResponse) Descriptor() ([]byte, []int) {
	return file_zhiplugin_v1_ui_proto_rawDescGZIP(), []int{14}
}

func (x *CtrlExportTemplatesResponse) GetTemplates() []*CtrlExportTemplateMsg {
	if x != nil {
		return x.Templates
	}
	return nil
}

type CtrlExportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TemplatePath  string                 `protobuf:"bytes,1,opt,name=template_path,json=templatePath,proto3" json:"template_path,omitempty"`
	Format        string                 `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"`
	OutputPath    string                 `protobuf:"bytes,3,opt,name=output_path,json=outputPath,proto3" json:"output_path,omitempty"`
	Prefix        string                 `protobuf:"bytes,4,opt,name=prefix,proto3" json:"prefix,omitempty"`
	DryRun        bool                   `protobuf:"varint,5,opt,name=dry_run,json=dryRun,proto3" json:"dry_run,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CtrlExportRequest) Reset() {
	*x = CtrlExportRequest{}
	mi := &file_zhiplugin_v1_ui_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CtrlExportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CtrlExportRequest) ProtoMessage() {}

func (x *CtrlExportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zhiplugin_v1_ui_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CtrlExportRequest.ProtoReflect.Descriptor instead.
func (*CtrlExportRequest) Descriptor() ([]byte, []int) {
	return file_zhiplugin_v1_ui_proto_rawDescGZIP(), []int{15}
}

func (x *CtrlExportRequest) GetTemplatePath() string {
	if x != nil {
		return x.TemplatePath
	}
	return ""
}

func (x *CtrlExportRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *CtrlExportRequest) GetOutputPath() string {
	if x != nil {
		return x.OutputPath
	}
	return ""
}

func (x *CtrlExportRequest) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *CtrlExportRequest) GetDryRun() bool {
	if x != nil {
		return x.DryRun
	}
	return false
}

type CtrlExportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	OutputPath    string                 `protobuf:"bytes,3,opt,name=output_path,json=outputPath,proto3" json:"output_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CtrlExportResponse) Reset() {
	*x = CtrlExportResponse{}
	mi := &file_zhiplugin_v1_ui_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CtrlExportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CtrlExportResponse) ProtoMessage() {}

func (x *CtrlExportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zhiplugin_v1_ui_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CtrlExportResponse.ProtoReflect.Descriptor instead.
func (*CtrlExportResponse) Descriptor() ([]byte, []int) {
	return file_zhiplugin_v1_ui_proto_rawDescGZIP(), []int{16}
}

func (x *CtrlExportResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CtrlExportResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CtrlExportResponse) GetOutputPath() string {
	if x != nil {
		return x.OutputPath
	}
	return ""
}

type CtrlApplyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        string                 `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CtrlApplyRequest) Reset() {
	*x = CtrlApplyRequest{}
	mi := &file_zhiplugin_v1_ui_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CtrlApplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CtrlApplyRequest) ProtoMessage() {}

func (x *CtrlApplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zhiplugin_v1_ui_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CtrlApplyRequest.ProtoReflect.Descriptor instead.
func (*CtrlApplyRequest) Descriptor() ([]byte, []int) {
	return file_zhiplugin_v1_ui_proto_rawDescGZIP(), []int{17}
}

func (x *CtrlApplyRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

// CtrlApplyResponse carries either an output event or the final result.
// When done is false, line and stream contain an output event.
// When done is true, exit_code and error contain the final result.
type CtrlApplyResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Done  bool                   `protobuf:"varint,1,opt,name=done,proto3" json:"done,omitempty"`
	// Output event fields (when done == false).
	Line   string `protobuf:"bytes,2,opt,name=line,proto3" json:"line,omitempty"`
	Stream string `protobuf:"bytes,3,opt,name=stream,proto3" json:"stream,omitempty"` // "stdout" or "stderr"
	// Result fields (when done == true).
	ExitCode      int32  `protobuf:"varint,4,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Error         string `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CtrlApplyResponse) Reset() {
	*x = CtrlApplyResponse{}
	mi := &file_zhiplugin_v1_ui_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CtrlApplyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CtrlApplyResponse) ProtoMessage() {}

func (x *CtrlApplyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zhiplugin_v1_ui_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CtrlApplyResponse.ProtoReflect.Descriptor instead.
func (*CtrlApplyResponse) Descriptor() ([]byte, []int) {
	return file_zhiplugin_v1_ui_proto_rawDescGZIP(), []int{18}
}

func (x *CtrlApplyResponse) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *CtrlApplyResponse) GetLine() string {
	if x != nil {
		return x.Line
	}
	return ""
}

func (x *CtrlApplyResponse) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

func (x *CtrlApplyResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *CtrlApplyResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// CtrlListComponentsRequest is intentionally empty.
type CtrlListComponentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CtrlListComponentsRequest) Reset() {
	*x = CtrlListComponentsRequest{}
	mi := &file_zhiplugin_v1_ui_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CtrlListComponentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CtrlListComponentsRequest) ProtoMessage() {}

func (x *CtrlListComponentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zhiplugin_v1_ui_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CtrlListComponentsRequest.ProtoReflect.Descriptor instead.
func (*CtrlListComponentsRequest) Descriptor() ([]byte, []int) {
	return file_zhiplugin_v1_ui_proto_rawDescGZIP(), []int{19}
}

type CtrlComponentInfoMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Enabled       bool                   `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Mandatory     bool                   `protobuf:"varint,4,opt,name=mandatory,proto3" json:"mandatory,omitempty"`
	Paths         []string               `protobuf:"bytes,5,rep,name=paths,proto3" json:"paths,omitempty"`
	Dependencies  []string               `protobuf:"bytes,6,rep,name=dependencies,proto3" json:"dependencies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CtrlComponentInfoMsg) Reset() {
	*x = CtrlComponentInfoMsg{}
	mi := &file_zhiplugin_v1_ui_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CtrlComponentInfoMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CtrlComponentInfoMsg) ProtoMessage() {}

func (x *CtrlComponentInfoMsg) ProtoReflect() protoreflect.Message {
	mi := &file_zhiplugin_v1_ui_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CtrlComponentInfoMsg.ProtoReflect.Descriptor instead.
func (*CtrlComponentInfoMsg) Descriptor() ([]byte, []int) {
	return file_zhiplugin_v1_ui_proto_rawDescGZIP(), []int{20}
}

func (x *CtrlComponentInfoMsg) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CtrlComponentInfoMsg) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CtrlComponentInfoMsg) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *CtrlComponentInfoMsg) GetMandatory() bool {
	if x != nil {
		return x.Mandatory
	}
	return false
}

func (x *CtrlComponentInfoMsg) GetPaths() []string {
	if x != nil {
		return x.Paths
	}
	return nil
}

func (x *CtrlComponentInfoMsg) GetDependencies() []string {
	if x != nil {
		return x.Dependencies
	}
	return nil
}

type CtrlListComponentsResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Components    []*CtrlComponentInfoMsg `protobuf:"bytes,1,rep,name=components,proto3" json:"components,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CtrlListComponentsResponse) Reset() {
	*x = CtrlListComponentsResponse{}
	mi := &file_zhiplugin_v1_ui_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CtrlListComponentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CtrlListComponentsResponse) ProtoMessage() {}

func (x *CtrlListComponentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zhiplugin_v1_ui_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CtrlListComponentsResponse.ProtoReflect.Descriptor instead.
func (*CtrlListComponentsResponse) Descriptor() ([]byte, []int) {
	return file_zhiplugin_v1_ui_proto_rawDescGZIP(), []int{21}
}

func (x *CtrlListComponentsResponse) GetComponents() []*CtrlComponentInfoMsg {
	if x != nil {
		return x.Components
	}
	return nil
}

type CtrlEnableComponentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CtrlEnableComponentRequest) Reset() {
	*x = CtrlEnableComponentRequest{}
	mi := &file_zhiplugin_v1_ui_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CtrlEnableComponentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CtrlEnableComponentRequest) ProtoMessage() {}

func (x *CtrlEnableComponentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zhiplugin_v1_ui_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CtrlEnableComponentRequest.ProtoReflect.Descriptor instead.
func (*CtrlEnableComponentRequest) Descriptor() ([]byte, []int) {
	return file_zhiplugin_v1_ui_proto_rawDescGZIP(), []int{22}
}

func (x *CtrlEnableComponentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CtrlEnableComponentResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// All components that were enabled (including auto-enabled dependencies).
	Enabled       []string `protobuf:"bytes,1,rep,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CtrlEnableComponentResponse) Reset() {
	*x = CtrlEnableComponentResponse{}
	mi := &file_zhiplugin_v1_ui_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CtrlEnableComponentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CtrlEnableComponentResponse) ProtoMessage() {}

func (x *CtrlEnableComponentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zhiplugin_v1_ui_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CtrlEnableComponentResponse.ProtoReflect.Descriptor instead.
func (*CtrlEnableComponentResponse) Descriptor() ([]byte, []int) {
	return file_zhiplugin_v1_ui_proto_rawDescGZIP(), []int{23}
}

func (x *CtrlEnableComponentResponse) GetEnabled() []string {
	if x != nil {
		return x.Enabled
	}
	return nil
}

type CtrlDisableComponentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CtrlDisableComponentRequest) Reset() {
	*x = CtrlDisableComponentRequest{}
	mi := &file_zhiplugin_v1_ui_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CtrlDisableComponentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CtrlDisableComponentRequest) ProtoMessage() {}

func (x *CtrlDisableComponentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zhiplugin_v1_ui_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CtrlDisableComponentRequest.ProtoReflect.Descriptor instead.
func (*CtrlDisableComponentRequest) Descriptor() ([]byte, []int) {
	return file_zhiplugin_v1_ui_proto_rawDescGZIP(), []int{24}
}

func (x *CtrlDisableComponentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// CtrlDisableComponentResponse is intentionally empty.
type CtrlDisableComponentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CtrlDisableComponentResponse) Reset() {
	*x = CtrlDisableComponentResponse{}
	mi := &file_zhiplugin_v1_ui_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CtrlDisableComponentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CtrlDisableComponentResponse) ProtoMessage() {}

func (x *CtrlDisableComponentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zhiplugin_v1_ui_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CtrlDisableComponentResponse.ProtoReflect.Descriptor instead.
func (*CtrlDisableComponentResponse) Descriptor() ([]byte, []int) {
	return file_zhiplugin_v1_ui_proto_rawDescGZIP(), []int{25}
}

// CtrlWorkspaceNameRequest is intentionally empty.
type CtrlWorkspaceNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CtrlWorkspaceNameRequest) Reset() {
	*x = CtrlWorkspaceNameRequest{}
	mi := &file_zhiplugin_v1_ui_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CtrlWorkspaceNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CtrlWorkspaceNameRequest) ProtoMessage() {}

func (x *CtrlWorkspaceNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zhiplugin_v1_ui_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CtrlWorkspaceNameRequest.ProtoReflect.Descriptor instead.
func (*CtrlWorkspaceNameRequest) Descriptor() ([]byte, []int) {
	return file_zhiplugin_v1_ui_proto_rawDescGZIP(), []int{26}
}

type CtrlWorkspaceNameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CtrlWorkspaceNameResponse) Reset() {
	*x = CtrlWorkspaceNameResponse{}
	mi := &file_zhiplugin_v1_ui_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CtrlWorkspaceNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CtrlWorkspaceNameResponse) ProtoMessage() {}

func (x *CtrlWorkspaceNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zhiplugin_v1_ui_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CtrlWorkspaceNameResponse.ProtoReflect.Descriptor instead.
func (*CtrlWorkspaceNameResponse) Descriptor() ([]byte, []int) {
	return file_zhiplugin_v1_ui_proto_rawDescGZIP(), []int{27}
}

func (x *CtrlWorkspaceNameResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_zhiplugin_v1_ui_proto protoreflect.FileDescriptor

const file_zhiplugin_v1_ui_proto_rawDesc = "" +
	"\n" +
	"\x15zhiplugin/v1/ui.proto\x12\fzhiplugin.v1\x1a\x19zhiplugin/v1/config.proto\">\n" +
	"\n" +
	"RunRequest\x120\n" +
	"\x14controller_broker_id\x18\x01 \x01(\rR\x12controllerBrokerId\"\r\n" +
	"\vRunResponse\"\x15\n" +
	"\x13CapabilitiesRequest\"9\n" +
	"\x14CapabilitiesResponse\x12!\n" +
	"\frequires_tty\x18\x01 \x01(\bR\vrequiresTty\"\x15\n" +
	"\x13CtrlLoadTreeRequest\"C\n" +
	"\x14CtrlLoadTreeResponse\x12+\n" +
	"\x04tree\x18\x01 \x03(\v2\x17.zhiplugin.v1.TreeEntryR\x04tree\"m\n" +
	"\x13CtrlSetValueRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1d\n" +
	"\n" +
	"value_json\x18\x02 \x01(\fR\tvalueJson\x12#\n" +
	"\rmetadata_json\x18\x03 \x01(\fR\fmetadataJson\"\x16\n" +
	"\x14CtrlSetValueResponse\"\x15\n" +
	"\x13CtrlValidateRequest\"S\n" +
	"\x14CtrlValidateResponse\x12;\n" +
	"\aresults\x18\x01 \x03(\v2!.zhiplugin.v1.ValidationResultMsgR\aresults\"%\n" +
	"\x13CtrlSaveTreeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x16\n" +
	"\x14CtrlSaveTreeResponse\"\x1c\n" +
	"\x1aCtrlExportTemplatesRequest\"\x8f\x01\n" +
	"\x15CtrlExportTemplateMsg\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\btemplate\x18\x02 \x01(\tR\btemplate\x12\x16\n" +
	"\x06format\x18\x03 \x01(\tR\x06format\x12\x16\n" +
	"\x06output\x18\x04 \x01(\tR\x06output\x12\x16\n" +
	"\x06prefix\x18\x05 \x01(\tR\x06prefix\"`\n" +
	"\x1bCtrlExportTemplatesResponse\x12A\n" +
	"\ttemplates\x18\x01 \x03(\v2#.zhiplugin.v1.CtrlExportTemplateMsgR\ttemplates\"\xa2\x01\n" +
	"\x11CtrlExportRequest\x12#\n" +
	"\rtemplate_path\x18\x01 \x01(\tR\ftemplatePath\x12\x16\n" +
	"\x06format\x18\x02 \x01(\tR\x06format\x12\x1f\n" +
	"\voutput_path\x18\x03 \x01(\tR\n" +
	"outputPath\x12\x16\n" +
	"\x06prefix\x18\x04 \x01(\tR\x06prefix\x12\x17\n" +
	"\adry_run\x18\x05 \x01(\bR\x06dryRun\"c\n" +
	"\x12CtrlExportResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1f\n" +
	"\voutput_path\x18\x03 \x01(\tR\n" +
	"outputPath\"*\n" +
	"\x10CtrlApplyRequest\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\"\x86\x01\n" +
	"\x11CtrlApplyResponse\x12\x12\n" +
	"\x04done\x18\x01 \x01(\bR\x04done\x12\x12\n" +
	"\x04line\x18\x02 \x01(\tR\x04line\x12\x16\n" +
	"\x06stream\x18\x03 \x01(\tR\x06stream\x12\x1b\n" +
	"\texit_code\x18\x04 \x01(\x05R\bexitCode\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\"\x1b\n" +
	"\x19CtrlListComponentsRequest\"\xbe\x01\n" +
	"\x14CtrlComponentInfoMsg\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x18\n" +
	"\aenabled\x18\x03 \x01(\bR\aenabled\x12\x1c\n" +
	"\tmandatory\x18\x04 \x01(\bR\tmandatory\x12\x14\n" +
	"\x05paths\x18\x05 \x03(\tR\x05paths\x12\"\n" +
	"\fdependencies\x18\x06 \x03(\tR\fdependencies\"`\n" +
	"\x1aCtrlListComponentsResponse\x12B\n" +
	"\n" +
	"components\x18\x01 \x03(\v2\".zhiplugin.v1.CtrlComponentInfoMsgR\n" +
	"components\"0\n" +
	"\x1aCtrlEnableComponentRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"7\n" +
	"\x1bCtrlEnableComponentResponse\x12\x18\n" +
	"\aenabled\x18\x01 \x03(\tR\aenabled\"1\n" +
	"\x1bCtrlDisableComponentRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x1e\n" +
	"\x1cCtrlDisableComponentResponse\"\x1a\n" +
	"\x18CtrlWorkspaceNameRequest\"/\n" +
	"\x19CtrlWorkspaceNameResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name2\x9e\x01\n" +
	"\tUIService\x12:\n" +
	"\x03Run\x12\x18.zhiplugin.v1.RunRequest\x1a\x19.zhiplugin.v1.RunResponse\x12U\n" +
	"\fCapabilities\x12!.zhiplugin.v1.CapabilitiesRequest\x1a\".zhiplugin.v1.CapabilitiesResponse2\xfc\a\n" +
	"\x13UIControllerService\x12Q\n" +
	"\bLoadTree\x12!.zhiplugin.v1.CtrlLoadTreeRequest\x1a\".zhiplugin.v1.CtrlLoadTreeResponse\x12Q\n" +
	"\bSetValue\x12!.zhiplugin.v1.CtrlSetValueRequest\x1a\".zhiplugin.v1.CtrlSetValueResponse\x12Q\n" +
	"\bValidate\x12!.zhiplugin.v1.CtrlValidateRequest\x1a\".zhiplugin.v1.CtrlValidateResponse\x12Q\n" +
	"\bSaveTree\x12!.zhiplugin.v1.CtrlSaveTreeRequest\x1a\".zhiplugin.v1.CtrlSaveTreeResponse\x12f\n" +
	"\x0fExportTemplates\x12(.zhiplugin.v1.CtrlExportTemplatesRequest\x1a).zhiplugin.v1.CtrlExportTemplatesResponse\x12K\n" +
	"\x06Export\x12\x1f.zhiplugin.v1.CtrlExportRequest\x1a .zhiplugin.v1.CtrlExportResponse\x12J\n" +
	"\x05Apply\x12\x1e.zhiplugin.v1.CtrlApplyRequest\x1a\x1f.zhiplugin.v1.CtrlApplyResponse0\x01\x12c\n" +
	"\x0eListComponents\x12'.zhiplugin.v1.CtrlListComponentsRequest\x1a(.zhiplugin.v1.CtrlListComponentsResponse\x12f\n" +
	"\x0fEnableComponent\x12(.zhiplugin.v1.CtrlEnableComponentRequest\x1a).zhiplugin.v1.CtrlEnableComponentResponse\x12i\n" +
	"\x10DisableComponent\x12).zhiplugin.v1.CtrlDisableComponentRequest\x1a*.zhiplugin.v1.CtrlDisableComponentResponse\x12`\n" +
	"\rWorkspaceName\x12&.zhiplugin.v1.CtrlWorkspaceNameRequest\x1a'.zhiplugin.v1.CtrlWorkspaceNameResponseB0Z.github.com/MrWong99/zhi/pkg/zhiplugin/ui/protob\x06proto3"

var (
	file_zhiplugin_v1_ui_proto_rawDescOnce sync.Once
	file_zhiplugin_v1_ui_proto_rawDescData []byte
)

func file_zhiplugin_v1_ui_proto_rawDescGZIP() []byte {
	file_zhiplugin_v1_ui_proto_rawDescOnce.Do(func() {
		file_zhiplugin_v1_ui_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_zhiplugin_v1_ui_proto_rawDesc), len(file_zhiplugin_v1_ui_proto_rawDesc)))
	})
	return file_zhiplugin_v1_ui_proto_rawDescData
}

var file_zhiplugin_v1_ui_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_zhiplugin_v1_ui_proto_goTypes = []any{
	(*RunRequest)(nil),                   // 0: zhiplugin.v1.RunRequest
	(*RunResponse)(nil),                  // 1: zhiplugin.v1.RunResponse
	(*CapabilitiesRequest)(nil),          // 2: zhiplugin.v1.CapabilitiesRequest
	(*CapabilitiesResponse)(nil),         // 3: zhiplugin.v1.CapabilitiesResponse
	(*CtrlLoadTreeRequest)(nil),          // 4: zhiplugin.v1.CtrlLoadTreeRequest
	(*CtrlLoadTreeResponse)(nil),         // 5: zhiplugin.v1.CtrlLoadTreeResponse
	(*CtrlSetValueRequest)(nil),          // 6: zhiplugin.v1.CtrlSetValueRequest
	(*CtrlSetValueResponse)(nil),         // 7: zhiplugin.v1.CtrlSetValueResponse
	(*CtrlValidateRequest)(nil),          // 8: zhiplugin.v1.CtrlValidateRequest
	(*CtrlValidateResponse)(nil),         // 9: zhiplugin.v1.CtrlValidateResponse
	(*CtrlSaveTreeRequest)(nil),          // 10: zhiplugin.v1.CtrlSaveTreeRequest
	(*CtrlSaveTreeResponse)(nil),         // 11: zhiplugin.v1.CtrlSaveTreeResponse
	(*CtrlExportTemplatesRequest)(nil),   // 12: zhiplugin.v1.CtrlExportTemplatesRequest
	(*CtrlExportTemplateMsg)(nil),        // 13: zhiplugin.v1.CtrlExportTemplateMsg
	(*CtrlExportTemplatesResponse)(nil),  // 14: zhiplugin.v1.CtrlExportTemplatesResponse
	(*CtrlExportRequest)(nil),            // 15: zhiplugin.v1.CtrlExportRequest
	(*CtrlExportResponse)(nil),           // 16: zhiplugin.v1.CtrlExportResponse
	(*CtrlApplyRequest)(nil),             // 17: zhiplugin.v1.CtrlApplyRequest
	(*CtrlApplyResponse)(nil),            // 18: zhiplugin.v1.CtrlApplyResponse
	(*CtrlListComponentsRequest)(nil),    // 19: zhiplugin.v1.CtrlListComponentsRequest
	(*CtrlComponentInfoMsg)(nil),         // 20: zhiplugin.v1.CtrlComponentInfoMsg
	(*CtrlListComponentsResponse)(nil),   // 21: zhiplugin.v1.CtrlListComponentsResponse
	(*CtrlEnableComponentRequest)(nil),   // 22: zhiplugin.v1.CtrlEnableComponentRequest
	(*CtrlEnableComponentResponse)(nil),  // 23: zhiplugin.v1.CtrlEnableComponentResponse
	(*CtrlDisableComponentRequest)(nil),  // 24: zhiplugin.v1.CtrlDisableComponentRequest
	(*CtrlDisableComponentResponse)(nil), // 25: zhiplugin.v1.CtrlDisableComponentResponse
	(*CtrlWorkspaceNameRequest)(nil),     // 26: zhiplugin.v1.CtrlWorkspaceNameRequest
	(*CtrlWorkspaceNameResponse)(nil),    // 27: zhiplugin.v1.CtrlWorkspaceNameResponse
	(*proto.TreeEntry)(nil),              // 28: zhiplugin.v1.TreeEntry
	(*proto.ValidationResultMsg)(nil),    // 29: zhiplugin.v1.ValidationResultMsg
}
var file_zhiplugin_v1_ui_proto_depIdxs = []int32{
	28, // 0: zhiplugin.v1.CtrlLoadTreeResponse.tree:type_name -> zhiplugin.v1.TreeEntry
	29, // 1: zhiplugin.v1.CtrlValidateResponse.results:type_name -> zhiplugin.v1.ValidationResultMsg
	13, // 2: zhiplugin.v1.CtrlExportTemplatesResponse.templates:type_name -> zhiplugin.v1.CtrlExportTemplateMsg
	20, // 3: zhiplugin.v1.CtrlListComponentsResponse.components:type_name -> zhiplugin.v1.CtrlComponentInfoMsg
	0,  // 4: zhiplugin.v1.UIService.Run:input_type -> zhiplugin.v1.RunRequest
	2,  // 5: zhiplugin.v1.UIService.Capabilities:input_type -> zhiplugin.v1.CapabilitiesRequest
	4,  // 6: zhiplugin.v1.UIControllerService.LoadTree:input_type -> zhiplugin.v1.CtrlLoadTreeRequest
	6,  // 7: zhiplugin.v1.UIControllerService.SetValue:input_type -> zhiplugin.v1.CtrlSetValueRequest
	8,  // 8: zhiplugin.v1.UIControllerService.Validate:input_type -> zhiplugin.v1.CtrlValidateRequest
	10, // 9: zhiplugin.v1.UIControllerService.SaveTree:input_type -> zhiplugin.v1.CtrlSaveTreeRequest
	12, // 10: zhiplugin.v1.UIControllerService.ExportTemplates:input_type -> zhiplugin.v1.CtrlExportTemplatesRequest
	15, // 11: zhiplugin.v1.UIControllerService.Export:input_type -> zhiplugin.v1.CtrlExportRequest
	17, // 12: zhiplugin.v1.UIControllerService.Apply:input_type -> zhiplugin.v1.CtrlApplyRequest
	19, // 13: zhiplugin.v1.UIControllerService.ListComponents:input_type -> zhiplugin.v1.CtrlListComponentsRequest
	22, // 14: zhiplugin.v1.UIControllerService.EnableComponent:input_type -> zhiplugin.v1.CtrlEnableComponentRequest
	24, // 15: zhiplugin.v1.UIControllerService.DisableComponent:input_type -> zhiplugin.v1.CtrlDisableComponentRequest
	26, // 16: zhiplugin.v1.UIControllerService.WorkspaceName:input_type -> zhiplugin.v1.CtrlWorkspaceNameRequest
	1,  // 17: zhiplugin.v1.UIService.Run:output_type -> zhiplugin.v1.RunResponse
	3,  // 18: zhiplugin.v1.UIService.Capabilities:output_type -> zhiplugin.v1.CapabilitiesResponse
	5,  // 19: zhiplugin.v1.UIControllerService.LoadTree:output_type -> zhiplugin.v1.CtrlLoadTreeResponse
	7,  // 20: zhiplugin.v1.UIControllerService.SetValue:output_type -> zhiplugin.v1.CtrlSetValueResponse
	9,  // 21: zhiplugin.v1.UIControllerService.Validate:output_type -> zhiplugin.v1.CtrlValidateResponse
	11, // 22: zhiplugin.v1.UIControllerService.SaveTree:output_type -> zhiplugin.v1.CtrlSaveTreeResponse
	14, // 23: zhiplugin.v1.UIControllerService.ExportTemplates:output_type -> zhiplugin.v1.CtrlExportTemplatesResponse
	16, // 24: zhiplugin.v1.UIControllerService.Export:output_type -> zhiplugin.v1.CtrlExportResponse
	18, // 25: zhiplugin.v1.UIControllerService.Apply:output_type -> zhiplugin.v1.CtrlApplyResponse
	21, // 26: zhiplugin.v1.UIControllerService.ListComponents:output_type -> zhiplugin.v1.CtrlListComponentsResponse
	23, // 27: zhiplugin.v1.UIControllerService.EnableComponent:output_type -> zhiplugin.v1.CtrlEnableComponentResponse
	25, // 28: zhiplugin.v1.UIControllerService.DisableComponent:output_type -> zhiplugin.v1.CtrlDisableComponentResponse
	27, // 29: zhiplugin.v1.UIControllerService.WorkspaceName:output_type -> zhiplugin.v1.CtrlWorkspaceNameResponse
	17, // [17:30] is the sub-list for method output_type
	4,  // [4:17] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_zhiplugin_v1_ui_proto_init() }
func file_zhiplugin_v1_ui_proto_init() {
	if File_zhiplugin_v1_ui_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_zhiplugin_v1_ui_proto_rawDesc), len(file_zhiplugin_v1_ui_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_zhiplugin_v1_ui_proto_goTypes,
		DependencyIndexes: file_zhiplugin_v1_ui_proto_depIdxs,
		MessageInfos:      file_zhiplugin_v1_ui_proto_msgTypes,
	}.Build()
	File_zhiplugin_v1_ui_proto = out.File
	file_zhiplugin_v1_ui_proto_goTypes = nil
	file_zhiplugin_v1_ui_proto_depIdxs = nil
}
