// Copyright 2025 Lukas Schmidt
// SPDX-License-Identifier: MIT

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: zhiplugin/v1/ui.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UIService_Run_FullMethodName          = "/zhiplugin.v1.UIService/Run"
	UIService_Capabilities_FullMethodName = "/zhiplugin.v1.UIService/Capabilities"
)

// UIServiceClient is the client API for UIService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// UIService is the gRPC interface every zhi UI plugin must implement.
// The host calls Run to start the UI, passing a broker ID that the plugin
// uses to connect back to the UIControllerService for core operations.
type UIServiceClient interface {
	// Run starts the UI and blocks until the user exits or the context is
	// cancelled. The request carries a broker ID for the UIControllerService
	// that the plugin must dial to perform operations on the zhi core.
	Run(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (*RunResponse, error)
	// Capabilities reports what this UI plugin supports.
	Capabilities(ctx context.Context, in *CapabilitiesRequest, opts ...grpc.CallOption) (*CapabilitiesResponse, error)
}

type uIServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUIServiceClient(cc grpc.ClientConnInterface) UIServiceClient {
	return &uIServiceClient{cc}
}

func (c *uIServiceClient) Run(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (*RunResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunResponse)
	err := c.cc.Invoke(ctx, UIService_Run_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uIServiceClient) Capabilities(ctx context.Context, in *CapabilitiesRequest, opts ...grpc.CallOption) (*CapabilitiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CapabilitiesResponse)
	err := c.cc.Invoke(ctx, UIService_Capabilities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UIServiceServer is the server API for UIService service.
// All implementations must embed UnimplementedUIServiceServer
// for forward compatibility.
//
// UIService is the gRPC interface every zhi UI plugin must implement.
// The host calls Run to start the UI, passing a broker ID that the plugin
// uses to connect back to the UIControllerService for core operations.
type UIServiceServer interface {
	// Run starts the UI and blocks until the user exits or the context is
	// cancelled. The request carries a broker ID for the UIControllerService
	// that the plugin must dial to perform operations on the zhi core.
	Run(context.Context, *RunRequest) (*RunResponse, error)
	// Capabilities reports what this UI plugin supports.
	Capabilities(context.Context, *CapabilitiesRequest) (*CapabilitiesResponse, error)
	mustEmbedUnimplementedUIServiceServer()
}

// UnimplementedUIServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUIServiceServer struct{}

func (UnimplementedUIServiceServer) Run(context.Context, *RunRequest) (*RunResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Run not implemented")
}
func (UnimplementedUIServiceServer) Capabilities(context.Context, *CapabilitiesRequest) (*CapabilitiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Capabilities not implemented")
}
func (UnimplementedUIServiceServer) mustEmbedUnimplementedUIServiceServer() {}
func (UnimplementedUIServiceServer) testEmbeddedByValue()                   {}

// UnsafeUIServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UIServiceServer will
// result in compilation errors.
type UnsafeUIServiceServer interface {
	mustEmbedUnimplementedUIServiceServer()
}

func RegisterUIServiceServer(s grpc.ServiceRegistrar, srv UIServiceServer) {
	// If the following call panics, it indicates UnimplementedUIServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UIService_ServiceDesc, srv)
}

func _UIService_Run_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UIServiceServer).Run(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UIService_Run_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UIServiceServer).Run(ctx, req.(*RunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UIService_Capabilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CapabilitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UIServiceServer).Capabilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UIService_Capabilities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UIServiceServer).Capabilities(ctx, req.(*CapabilitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UIService_ServiceDesc is the grpc.ServiceDesc for UIService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UIService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "zhiplugin.v1.UIService",
	HandlerType: (*UIServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Run",
			Handler:    _UIService_Run_Handler,
		},
		{
			MethodName: "Capabilities",
			Handler:    _UIService_Capabilities_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "zhiplugin/v1/ui.proto",
}

const (
	UIControllerService_LoadTree_FullMethodName         = "/zhiplugin.v1.UIControllerService/LoadTree"
	UIControllerService_SetValue_FullMethodName         = "/zhiplugin.v1.UIControllerService/SetValue"
	UIControllerService_Validate_FullMethodName         = "/zhiplugin.v1.UIControllerService/Validate"
	UIControllerService_SaveTree_FullMethodName         = "/zhiplugin.v1.UIControllerService/SaveTree"
	UIControllerService_ExportTemplates_FullMethodName  = "/zhiplugin.v1.UIControllerService/ExportTemplates"
	UIControllerService_Export_FullMethodName           = "/zhiplugin.v1.UIControllerService/Export"
	UIControllerService_Apply_FullMethodName            = "/zhiplugin.v1.UIControllerService/Apply"
	UIControllerService_ListComponents_FullMethodName   = "/zhiplugin.v1.UIControllerService/ListComponents"
	UIControllerService_EnableComponent_FullMethodName  = "/zhiplugin.v1.UIControllerService/EnableComponent"
	UIControllerService_DisableComponent_FullMethodName = "/zhiplugin.v1.UIControllerService/DisableComponent"
	UIControllerService_WorkspaceName_FullMethodName    = "/zhiplugin.v1.UIControllerService/WorkspaceName"
)

// UIControllerServiceClient is the client API for UIControllerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// UIControllerService is served by the zhi host via the GRPCBroker.
// UI plugins call these methods to perform operations on the core engine.
type UIControllerServiceClient interface {
	// LoadTree loads or reloads the full configuration tree.
	LoadTree(ctx context.Context, in *CtrlLoadTreeRequest, opts ...grpc.CallOption) (*CtrlLoadTreeResponse, error)
	// SetValue stores a configuration value at the given path.
	SetValue(ctx context.Context, in *CtrlSetValueRequest, opts ...grpc.CallOption) (*CtrlSetValueResponse, error)
	// Validate runs validation on the current configuration tree.
	Validate(ctx context.Context, in *CtrlValidateRequest, opts ...grpc.CallOption) (*CtrlValidateResponse, error)
	// SaveTree persists the current tree to the store.
	SaveTree(ctx context.Context, in *CtrlSaveTreeRequest, opts ...grpc.CallOption) (*CtrlSaveTreeResponse, error)
	// ExportTemplates returns the configured export templates.
	ExportTemplates(ctx context.Context, in *CtrlExportTemplatesRequest, opts ...grpc.CallOption) (*CtrlExportTemplatesResponse, error)
	// Export runs a single export operation.
	Export(ctx context.Context, in *CtrlExportRequest, opts ...grpc.CallOption) (*CtrlExportResponse, error)
	// Apply runs the apply command and streams output events back.
	Apply(ctx context.Context, in *CtrlApplyRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CtrlApplyResponse], error)
	// ListComponents returns all components with their current state.
	ListComponents(ctx context.Context, in *CtrlListComponentsRequest, opts ...grpc.CallOption) (*CtrlListComponentsResponse, error)
	// EnableComponent enables a component and its dependencies.
	EnableComponent(ctx context.Context, in *CtrlEnableComponentRequest, opts ...grpc.CallOption) (*CtrlEnableComponentResponse, error)
	// DisableComponent disables a component.
	DisableComponent(ctx context.Context, in *CtrlDisableComponentRequest, opts ...grpc.CallOption) (*CtrlDisableComponentResponse, error)
	// WorkspaceName returns the workspace display name.
	WorkspaceName(ctx context.Context, in *CtrlWorkspaceNameRequest, opts ...grpc.CallOption) (*CtrlWorkspaceNameResponse, error)
}

type uIControllerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUIControllerServiceClient(cc grpc.ClientConnInterface) UIControllerServiceClient {
	return &uIControllerServiceClient{cc}
}

func (c *uIControllerServiceClient) LoadTree(ctx context.Context, in *CtrlLoadTreeRequest, opts ...grpc.CallOption) (*CtrlLoadTreeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CtrlLoadTreeResponse)
	err := c.cc.Invoke(ctx, UIControllerService_LoadTree_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uIControllerServiceClient) SetValue(ctx context.Context, in *CtrlSetValueRequest, opts ...grpc.CallOption) (*CtrlSetValueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CtrlSetValueResponse)
	err := c.cc.Invoke(ctx, UIControllerService_SetValue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uIControllerServiceClient) Validate(ctx context.Context, in *CtrlValidateRequest, opts ...grpc.CallOption) (*CtrlValidateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CtrlValidateResponse)
	err := c.cc.Invoke(ctx, UIControllerService_Validate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uIControllerServiceClient) SaveTree(ctx context.Context, in *CtrlSaveTreeRequest, opts ...grpc.CallOption) (*CtrlSaveTreeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CtrlSaveTreeResponse)
	err := c.cc.Invoke(ctx, UIControllerService_SaveTree_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uIControllerServiceClient) ExportTemplates(ctx context.Context, in *CtrlExportTemplatesRequest, opts ...grpc.CallOption) (*CtrlExportTemplatesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CtrlExportTemplatesResponse)
	err := c.cc.Invoke(ctx, UIControllerService_ExportTemplates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uIControllerServiceClient) Export(ctx context.Context, in *CtrlExportRequest, opts ...grpc.CallOption) (*CtrlExportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CtrlExportResponse)
	err := c.cc.Invoke(ctx, UIControllerService_Export_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uIControllerServiceClient) Apply(ctx context.Context, in *CtrlApplyRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CtrlApplyResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &UIControllerService_ServiceDesc.Streams[0], UIControllerService_Apply_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CtrlApplyRequest, CtrlApplyResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type UIControllerService_ApplyClient = grpc.ServerStreamingClient[CtrlApplyResponse]

func (c *uIControllerServiceClient) ListComponents(ctx context.Context, in *CtrlListComponentsRequest, opts ...grpc.CallOption) (*CtrlListComponentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CtrlListComponentsResponse)
	err := c.cc.Invoke(ctx, UIControllerService_ListComponents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uIControllerServiceClient) EnableComponent(ctx context.Context, in *CtrlEnableComponentRequest, opts ...grpc.CallOption) (*CtrlEnableComponentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CtrlEnableComponentResponse)
	err := c.cc.Invoke(ctx, UIControllerService_EnableComponent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uIControllerServiceClient) DisableComponent(ctx context.Context, in *CtrlDisableComponentRequest, opts ...grpc.CallOption) (*CtrlDisableComponentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CtrlDisableComponentResponse)
	err := c.cc.Invoke(ctx, UIControllerService_DisableComponent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uIControllerServiceClient) WorkspaceName(ctx context.Context, in *CtrlWorkspaceNameRequest, opts ...grpc.CallOption) (*CtrlWorkspaceNameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CtrlWorkspaceNameResponse)
	err := c.cc.Invoke(ctx, UIControllerService_WorkspaceName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UIControllerServiceServer is the server API for UIControllerService service.
// All implementations must embed UnimplementedUIControllerServiceServer
// for forward compatibility.
//
// UIControllerService is served by the zhi host via the GRPCBroker.
// UI plugins call these methods to perform operations on the core engine.
type UIControllerServiceServer interface {
	// LoadTree loads or reloads the full configuration tree.
	LoadTree(context.Context, *CtrlLoadTreeRequest) (*CtrlLoadTreeResponse, error)
	// SetValue stores a configuration value at the given path.
	SetValue(context.Context, *CtrlSetValueRequest) (*CtrlSetValueResponse, error)
	// Validate runs validation on the current configuration tree.
	Validate(context.Context, *CtrlValidateRequest) (*CtrlValidateResponse, error)
	// SaveTree persists the current tree to the store.
	SaveTree(context.Context, *CtrlSaveTreeRequest) (*CtrlSaveTreeResponse, error)
	// ExportTemplates returns the configured export templates.
	ExportTemplates(context.Context, *CtrlExportTemplatesRequest) (*CtrlExportTemplatesResponse, error)
	// Export runs a single export operation.
	Export(context.Context, *CtrlExportRequest) (*CtrlExportResponse, error)
	// Apply runs the apply command and streams output events back.
	Apply(*CtrlApplyRequest, grpc.ServerStreamingServer[CtrlApplyResponse]) error
	// ListComponents returns all components with their current state.
	ListComponents(context.Context, *CtrlListComponentsRequest) (*CtrlListComponentsResponse, error)
	// EnableComponent enables a component and its dependencies.
	EnableComponent(context.Context, *CtrlEnableComponentRequest) (*CtrlEnableComponentResponse, error)
	// DisableComponent disables a component.
	DisableComponent(context.Context, *CtrlDisableComponentRequest) (*CtrlDisableComponentResponse, error)
	// WorkspaceName returns the workspace display name.
	WorkspaceName(context.Context, *CtrlWorkspaceNameRequest) (*CtrlWorkspaceNameResponse, error)
	mustEmbedUnimplementedUIControllerServiceServer()
}

// UnimplementedUIControllerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUIControllerServiceServer struct{}

func (UnimplementedUIControllerServiceServer) LoadTree(context.Context, *CtrlLoadTreeRequest) (*CtrlLoadTreeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LoadTree not implemented")
}
func (UnimplementedUIControllerServiceServer) SetValue(context.Context, *CtrlSetValueRequest) (*CtrlSetValueResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetValue not implemented")
}
func (UnimplementedUIControllerServiceServer) Validate(context.Context, *CtrlValidateRequest) (*CtrlValidateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Validate not implemented")
}
func (UnimplementedUIControllerServiceServer) SaveTree(context.Context, *CtrlSaveTreeRequest) (*CtrlSaveTreeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveTree not implemented")
}
func (UnimplementedUIControllerServiceServer) ExportTemplates(context.Context, *CtrlExportTemplatesRequest) (*CtrlExportTemplatesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExportTemplates not implemented")
}
func (UnimplementedUIControllerServiceServer) Export(context.Context, *CtrlExportRequest) (*CtrlExportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Export not implemented")
}
func (UnimplementedUIControllerServiceServer) Apply(*CtrlApplyRequest, grpc.ServerStreamingServer[CtrlApplyResponse]) error {
	return status.Error(codes.Unimplemented, "method Apply not implemented")
}
func (UnimplementedUIControllerServiceServer) ListComponents(context.Context, *CtrlListComponentsRequest) (*CtrlListComponentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListComponents not implemented")
}
func (UnimplementedUIControllerServiceServer) EnableComponent(context.Context, *CtrlEnableComponentRequest) (*CtrlEnableComponentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EnableComponent not implemented")
}
func (UnimplementedUIControllerServiceServer) DisableComponent(context.Context, *CtrlDisableComponentRequest) (*CtrlDisableComponentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DisableComponent not implemented")
}
func (UnimplementedUIControllerServiceServer) WorkspaceName(context.Context, *CtrlWorkspaceNameRequest) (*CtrlWorkspaceNameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WorkspaceName not implemented")
}
func (UnimplementedUIControllerServiceServer) mustEmbedUnimplementedUIControllerServiceServer() {}
func (UnimplementedUIControllerServiceServer) testEmbeddedByValue()                             {}

// UnsafeUIControllerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UIControllerServiceServer will
// result in compilation errors.
type UnsafeUIControllerServiceServer interface {
	mustEmbedUnimplementedUIControllerServiceServer()
}

func RegisterUIControllerServiceServer(s grpc.ServiceRegistrar, srv UIControllerServiceServer) {
	// If the following call panics, it indicates UnimplementedUIControllerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UIControllerService_ServiceDesc, srv)
}

func _UIControllerService_LoadTree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CtrlLoadTreeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UIControllerServiceServer).LoadTree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UIControllerService_LoadTree_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UIControllerServiceServer).LoadTree(ctx, req.(*CtrlLoadTreeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UIControllerService_SetValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CtrlSetValueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UIControllerServiceServer).SetValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UIControllerService_SetValue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UIControllerServiceServer).SetValue(ctx, req.(*CtrlSetValueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UIControllerService_Validate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CtrlValidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UIControllerServiceServer).Validate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UIControllerService_Validate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UIControllerServiceServer).Validate(ctx, req.(*CtrlValidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UIControllerService_SaveTree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CtrlSaveTreeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UIControllerServiceServer).SaveTree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UIControllerService_SaveTree_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UIControllerServiceServer).SaveTree(ctx, req.(*CtrlSaveTreeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UIControllerService_ExportTemplates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CtrlExportTemplatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UIControllerServiceServer).ExportTemplates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UIControllerService_ExportTemplates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UIControllerServiceServer).ExportTemplates(ctx, req.(*CtrlExportTemplatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UIControllerService_Export_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CtrlExportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UIControllerServiceServer).Export(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UIControllerService_Export_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UIControllerServiceServer).Export(ctx, req.(*CtrlExportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UIControllerService_Apply_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CtrlApplyRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(UIControllerServiceServer).Apply(m, &grpc.GenericServerStream[CtrlApplyRequest, CtrlApplyResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type UIControllerService_ApplyServer = grpc.ServerStreamingServer[CtrlApplyResponse]

func _UIControllerService_ListComponents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CtrlListComponentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UIControllerServiceServer).ListComponents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UIControllerService_ListComponents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UIControllerServiceServer).ListComponents(ctx, req.(*CtrlListComponentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UIControllerService_EnableComponent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CtrlEnableComponentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UIControllerServiceServer).EnableComponent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UIControllerService_EnableComponent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UIControllerServiceServer).EnableComponent(ctx, req.(*CtrlEnableComponentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UIControllerService_DisableComponent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CtrlDisableComponentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UIControllerServiceServer).DisableComponent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UIControllerService_DisableComponent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UIControllerServiceServer).DisableComponent(ctx, req.(*CtrlDisableComponentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UIControllerService_WorkspaceName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CtrlWorkspaceNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UIControllerServiceServer).WorkspaceName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UIControllerService_WorkspaceName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UIControllerServiceServer).WorkspaceName(ctx, req.(*CtrlWorkspaceNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UIControllerService_ServiceDesc is the grpc.ServiceDesc for UIControllerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UIControllerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "zhiplugin.v1.UIControllerService",
	HandlerType: (*UIControllerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LoadTree",
			Handler:    _UIControllerService_LoadTree_Handler,
		},
		{
			MethodName: "SetValue",
			Handler:    _UIControllerService_SetValue_Handler,
		},
		{
			MethodName: "Validate",
			Handler:    _UIControllerService_Validate_Handler,
		},
		{
			MethodName: "SaveTree",
			Handler:    _UIControllerService_SaveTree_Handler,
		},
		{
			MethodName: "ExportTemplates",
			Handler:    _UIControllerService_ExportTemplates_Handler,
		},
		{
			MethodName: "Export",
			Handler:    _UIControllerService_Export_Handler,
		},
		{
			MethodName: "ListComponents",
			Handler:    _UIControllerService_ListComponents_Handler,
		},
		{
			MethodName: "EnableComponent",
			Handler:    _UIControllerService_EnableComponent_Handler,
		},
		{
			MethodName: "DisableComponent",
			Handler:    _UIControllerService_DisableComponent_Handler,
		},
		{
			MethodName: "WorkspaceName",
			Handler:    _UIControllerService_WorkspaceName_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Apply",
			Handler:       _UIControllerService_Apply_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "zhiplugin/v1/ui.proto",
}
